import React from 'react';
import { ChatTheme } from './themesPart1';
import { 
  LEAVES_PATTERN, 
  STARS_PATTERN, 
  WHATSAPP_DOODLE, 
  ZENOA_AESTHETIC_MICRO_PATTERN,
  LOVE_ROMANCE_PATTERN,
  CUTE_ANIMALS_PATTERN,
  KIDS_WORLD_PATTERN,
  PREMIUM_MINIMAL_LINEN,
  PROFESSIONAL_TECH_PATTERN,
  DINO_ADVENTURE_PATTERN,
  SKY_CLOUDS_PATTERN,
  AURORA_STARRY_PATTERN,
  JUNGLE_BOTANICAL_PATTERN,
  CYBERPUNK_GRID_PATTERN,
  CORPORATE_EXECUTIVE_PATTERN,
  OCEAN_WAVES_PATTERN,
  SAKURA_BLOSSOM_PATTERN,
  PIXEL_RETRO_PATTERN,
  GALAXY_COSMOS_PATTERN,
  SWEET_CANDY_PATTERN
} from '../assets/wallpapers';

export const THEMES_PART2: ChatTheme[] = [
  // ==================== 5. NATURE & BOTANY CONTINUED (26-30) ====================
  {
    id: 'nature_bamboo_grove',
    name: 'Bamboo Grove Zen',
    category: 'nature',
    description: 'Tranquil bamboo leaves & moss green background with serene sage send button.',
    bgClass: 'bg-[#f4f7f4] dark:bg-[#0f1912] text-emerald-950 dark:text-emerald-100',
    bgStyle: {
      backgroundImage: JUNGLE_BOTANICAL_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '200px 200px'
    },
    bubble: {
      sentBg: 'bg-[#15803d] dark:bg-[#22c55e]',
      sentText: 'text-white dark:text-slate-950 font-bold',
      receivedBg: 'bg-white dark:bg-[#1a2b1f]',
      receivedText: 'text-emerald-950 dark:text-emerald-100',
      borderStyle: 'border border-emerald-200 dark:border-emerald-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-emerald-100 dark:text-emerald-950',
      subtextReceived: 'text-emerald-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-emerald-600 underline'
    },
    previewGradient: 'from-[#f4f7f4] to-[#dcfce7] dark:from-[#0f1912] to-[#1c3323]',
    badge: '🎋 Bamboo',
    headerBg: 'bg-[#f4f7f4]/90 dark:bg-[#0f1912]/90 backdrop-blur-md',
    headerBorder: 'border-b border-emerald-200 dark:border-emerald-900/50',
    headerText: 'text-emerald-950 dark:text-emerald-100',
    headerSubtext: 'text-emerald-600 dark:text-emerald-400',
    composerBg: 'bg-[#dcfce7]/60 dark:bg-[#0a120c]',
    composerBorder: 'border-t border-emerald-200 dark:border-emerald-900/50',
    innerInputBg: 'bg-white dark:bg-[#1f3325]',
    innerInputBorder: 'border-emerald-300 dark:border-emerald-800',
    innerInputText: 'text-emerald-950 dark:text-emerald-100',
    actionButtonText: 'text-emerald-600 dark:text-emerald-400',
    actionButtonHoverBg: 'hover:bg-emerald-100 dark:hover:bg-emerald-950/60',
    actionButtonActiveBg: 'bg-emerald-200 dark:bg-emerald-900 text-emerald-800',
    accentBg: 'bg-emerald-600 hover:bg-emerald-500 dark:bg-emerald-400 dark:hover:bg-emerald-300',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'nature_cherry_blossom',
    name: 'Sakura Cherry Blossom',
    category: 'nature',
    description: 'Japanese sakura garden with floating petals and soft blossom pink controls.',
    bgClass: 'bg-[#fff1f2] dark:bg-[#220c15] text-rose-950 dark:text-rose-100',
    bgStyle: {
      backgroundImage: SAKURA_BLOSSOM_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '200px 200px'
    },
    bubble: {
      sentBg: 'bg-[#e11d48] dark:bg-[#fb7185]',
      sentText: 'text-white dark:text-slate-950 font-medium',
      receivedBg: 'bg-white dark:bg-[#321320]',
      receivedText: 'text-rose-950 dark:text-rose-100',
      borderStyle: 'border border-rose-200 dark:border-rose-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-rose-100 dark:text-rose-950',
      subtextReceived: 'text-rose-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-rose-600 underline'
    },
    previewGradient: 'from-[#fff1f2] to-[#ffe4e6] dark:from-[#220c15] to-[#3a1524]',
    badge: '🌸 Sakura',
    headerBg: 'bg-[#fff1f2]/90 dark:bg-[#220c15]/90 backdrop-blur-md',
    headerBorder: 'border-b border-rose-200 dark:border-rose-900/50',
    headerText: 'text-rose-950 dark:text-rose-100',
    headerSubtext: 'text-rose-600 dark:text-rose-400',
    composerBg: 'bg-[#ffe4e6]/60 dark:bg-[#18080f]',
    composerBorder: 'border-t border-rose-200 dark:border-rose-900/50',
    innerInputBg: 'bg-white dark:bg-[#2b101c]',
    innerInputBorder: 'border-rose-300 dark:border-rose-800',
    innerInputText: 'text-rose-950 dark:text-rose-100',
    actionButtonText: 'text-rose-600 dark:text-rose-400',
    actionButtonHoverBg: 'hover:bg-rose-100 dark:hover:bg-rose-950/60',
    actionButtonActiveBg: 'bg-rose-200 dark:bg-rose-900 text-rose-800',
    accentBg: 'bg-rose-600 hover:bg-rose-500 dark:bg-rose-400 dark:hover:bg-rose-300',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'nature_autumn_maple',
    name: 'Autumn Maple Forest',
    category: 'nature',
    description: 'Cozy autumn maple rust background with rich crimson maple controls.',
    bgClass: 'bg-[#fff7ed] dark:bg-[#230f07] text-amber-950 dark:text-amber-100',
    bgStyle: {
      backgroundImage: LEAVES_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '120px 120px'
    },
    bubble: {
      sentBg: 'bg-[#c2410c] dark:bg-[#ea580c]',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-white dark:bg-[#34180d]',
      receivedText: 'text-amber-950 dark:text-amber-100',
      borderStyle: 'border border-orange-200 dark:border-orange-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-orange-100',
      subtextReceived: 'text-orange-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-orange-600 underline'
    },
    previewGradient: 'from-[#fff7ed] to-[#ffedd5] dark:from-[#230f07] to-[#3b1a0d]',
    badge: '🍁 Autumn',
    headerBg: 'bg-[#fff7ed]/90 dark:bg-[#230f07]/90 backdrop-blur-md',
    headerBorder: 'border-b border-orange-200 dark:border-orange-900/50',
    headerText: 'text-amber-950 dark:text-amber-100',
    headerSubtext: 'text-orange-600 dark:text-orange-400',
    composerBg: 'bg-[#ffedd5]/60 dark:bg-[#180a04]',
    composerBorder: 'border-t border-orange-200 dark:border-orange-900/50',
    innerInputBg: 'bg-white dark:bg-[#2f150b]',
    innerInputBorder: 'border-orange-300 dark:border-orange-800',
    innerInputText: 'text-amber-950 dark:text-amber-100',
    actionButtonText: 'text-orange-600 dark:text-orange-400',
    actionButtonHoverBg: 'hover:bg-orange-100 dark:hover:bg-orange-950/60',
    actionButtonActiveBg: 'bg-orange-200 dark:bg-orange-900 text-orange-800',
    accentBg: 'bg-orange-600 hover:bg-orange-500 dark:bg-orange-500 dark:hover:bg-orange-400',
    accentText: 'text-white font-bold'
  },
  {
    id: 'nature_botanical_garden',
    name: 'Botanical Sage Garden',
    category: 'nature',
    description: 'Serene sage green botanical aesthetic with muted olive controls.',
    bgClass: 'bg-[#f0fdf4] dark:bg-[#0c1e13] text-emerald-950 dark:text-emerald-100',
    bgStyle: {
      backgroundImage: JUNGLE_BOTANICAL_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '240px 240px'
    },
    bubble: {
      sentBg: 'bg-[#047857] dark:bg-[#10b981]',
      sentText: 'text-white dark:text-slate-950 font-bold',
      receivedBg: 'bg-white dark:bg-[#152e1e]',
      receivedText: 'text-emerald-950 dark:text-emerald-100',
      borderStyle: 'border border-emerald-200 dark:border-emerald-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-emerald-100 dark:text-emerald-950',
      subtextReceived: 'text-emerald-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-emerald-600 underline'
    },
    previewGradient: 'from-[#f0fdf4] to-[#dcfce7] dark:from-[#0c1e13] to-[#183623]',
    badge: '🌿 Botanical',
    headerBg: 'bg-[#f0fdf4]/90 dark:bg-[#0c1e13]/90 backdrop-blur-md',
    headerBorder: 'border-b border-emerald-200 dark:border-emerald-900/50',
    headerText: 'text-emerald-950 dark:text-emerald-100',
    headerSubtext: 'text-emerald-600 dark:text-emerald-400',
    composerBg: 'bg-[#dcfce7]/60 dark:bg-[#08140c]',
    composerBorder: 'border-t border-emerald-200 dark:border-emerald-900/50',
    innerInputBg: 'bg-white dark:bg-[#193623]',
    innerInputBorder: 'border-emerald-300 dark:border-emerald-800',
    innerInputText: 'text-emerald-950 dark:text-emerald-100',
    actionButtonText: 'text-emerald-600 dark:text-emerald-400',
    actionButtonHoverBg: 'hover:bg-emerald-100 dark:hover:bg-emerald-950/60',
    actionButtonActiveBg: 'bg-emerald-200 dark:bg-emerald-900 text-emerald-800',
    accentBg: 'bg-emerald-600 hover:bg-emerald-500 dark:bg-emerald-400 dark:hover:bg-emerald-300',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'nature_desert_oasis',
    name: 'Desert Oasis Terracotta',
    category: 'nature',
    description: 'Warm terracotta desert sand with warm oasis amber send controls.',
    bgClass: 'bg-[#fffbeb] dark:bg-[#201509] text-amber-950 dark:text-amber-100',
    bgStyle: {
      backgroundImage: PREMIUM_MINIMAL_LINEN,
      backgroundRepeat: 'repeat',
      backgroundSize: '32px 32px'
    },
    bubble: {
      sentBg: 'bg-[#b45309] dark:bg-[#d97706]',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-white dark:bg-[#302110]',
      receivedText: 'text-amber-950 dark:text-amber-100',
      borderStyle: 'border border-amber-200 dark:border-amber-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-amber-100',
      subtextReceived: 'text-amber-500',
      linkSent: 'text-white underline',
      linkReceived: 'text-amber-700 underline'
    },
    previewGradient: 'from-[#fffbeb] to-[#fef3c7] dark:from-[#201509] to-[#362410]',
    badge: '🏜️ Desert Oasis',
    headerBg: 'bg-[#fffbeb]/90 dark:bg-[#201509]/90 backdrop-blur-md',
    headerBorder: 'border-b border-amber-200 dark:border-amber-900/50',
    headerText: 'text-amber-950 dark:text-amber-100',
    headerSubtext: 'text-amber-700 dark:text-amber-400',
    composerBg: 'bg-[#fef3c7]/60 dark:bg-[#160e05]',
    composerBorder: 'border-t border-amber-200 dark:border-amber-900/50',
    innerInputBg: 'bg-white dark:bg-[#2b1c0d]',
    innerInputBorder: 'border-amber-300 dark:border-amber-800',
    innerInputText: 'text-amber-950 dark:text-amber-100',
    actionButtonText: 'text-amber-700 dark:text-amber-400',
    actionButtonHoverBg: 'hover:bg-amber-100 dark:hover:bg-amber-950/60',
    actionButtonActiveBg: 'bg-amber-200 dark:bg-amber-900 text-amber-900',
    accentBg: 'bg-amber-600 hover:bg-amber-700 dark:bg-amber-500 dark:hover:bg-amber-400',
    accentText: 'text-white font-bold'
  },

  // ==================== 6. SKY & CLOUDS (31-36) ====================
  {
    id: 'sky_daylight_clouds',
    name: 'Daylight Sky & Clouds',
    category: 'sky',
    description: 'Bright sky blue background with fluffy white clouds and cyan send button.',
    bgClass: 'bg-[#f0f9ff] dark:bg-[#071d2e] text-sky-950 dark:text-sky-100',
    bgStyle: {
      backgroundImage: SKY_CLOUDS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '240px 240px'
    },
    bubble: {
      sentBg: 'bg-[#0284c7] dark:bg-[#38bdf8]',
      sentText: 'text-white dark:text-slate-950 font-bold',
      receivedBg: 'bg-white dark:bg-[#122e47]',
      receivedText: 'text-sky-950 dark:text-sky-100',
      borderStyle: 'border border-sky-200 dark:border-sky-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-sky-100 dark:text-slate-900',
      subtextReceived: 'text-sky-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-sky-600 underline'
    },
    previewGradient: 'from-[#f0f9ff] to-[#e0f2fe] dark:from-[#071d2e] to-[#123654]',
    badge: '☁️ Daylight Sky',
    headerBg: 'bg-[#f0f9ff]/90 dark:bg-[#071d2e]/90 backdrop-blur-md',
    headerBorder: 'border-b border-sky-200 dark:border-sky-900/50',
    headerText: 'text-sky-950 dark:text-sky-100',
    headerSubtext: 'text-sky-600 dark:text-sky-400',
    composerBg: 'bg-[#e0f2fe]/60 dark:bg-[#04121d]',
    composerBorder: 'border-t border-sky-200 dark:border-sky-900/50',
    innerInputBg: 'bg-white dark:bg-[#112a42]',
    innerInputBorder: 'border-sky-300 dark:border-sky-800',
    innerInputText: 'text-sky-950 dark:text-sky-100',
    actionButtonText: 'text-sky-600 dark:text-sky-400',
    actionButtonHoverBg: 'hover:bg-sky-100 dark:hover:bg-sky-950/60',
    actionButtonActiveBg: 'bg-sky-200 dark:bg-sky-900 text-sky-800',
    accentBg: 'bg-sky-600 hover:bg-sky-500 dark:bg-sky-400 dark:hover:bg-sky-300',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'sky_sunset_horizon',
    name: 'Sunset Horizon Glow',
    category: 'sky',
    description: 'Violet & orange horizon sky with sunset amber controls.',
    bgClass: 'bg-[#fff7ed] dark:bg-[#200e1e] text-amber-950 dark:text-amber-100',
    bgStyle: {
      backgroundImage: SKY_CLOUDS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '240px 240px'
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-orange-500 to-rose-500',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-white dark:bg-[#32172f]',
      receivedText: 'text-amber-950 dark:text-amber-100',
      borderStyle: 'border border-orange-200 dark:border-orange-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-orange-100',
      subtextReceived: 'text-orange-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-orange-600 underline'
    },
    previewGradient: 'from-[#fff7ed] to-[#ffedd5] dark:from-[#200e1e] to-[#3a1837]',
    badge: '🌄 Sunset Horizon',
    headerBg: 'bg-[#fff7ed]/90 dark:bg-[#200e1e]/90 backdrop-blur-md',
    headerBorder: 'border-b border-orange-200 dark:border-orange-900/50',
    headerText: 'text-amber-950 dark:text-amber-100',
    headerSubtext: 'text-orange-600 dark:text-orange-400',
    composerBg: 'bg-[#ffedd5]/60 dark:bg-[#160814]',
    composerBorder: 'border-t border-orange-200 dark:border-orange-900/50',
    innerInputBg: 'bg-white dark:bg-[#2d122a]',
    innerInputBorder: 'border-orange-300 dark:border-orange-800',
    innerInputText: 'text-amber-950 dark:text-amber-100',
    actionButtonText: 'text-orange-600 dark:text-orange-400',
    actionButtonHoverBg: 'hover:bg-orange-100 dark:hover:bg-orange-950/60',
    actionButtonActiveBg: 'bg-orange-200 dark:bg-orange-900 text-orange-800',
    accentBg: 'bg-gradient-to-r from-orange-500 to-rose-500 hover:brightness-110',
    accentText: 'text-white font-bold'
  },
  {
    id: 'sky_aurora_borealis',
    name: 'Aurora Borealis Lights',
    category: 'sky',
    description: 'Ethereal northern lights dark sky with electric aurora teal controls.',
    bgClass: 'bg-[#05131a] text-teal-100',
    bgStyle: {
      backgroundColor: '#05131a',
      backgroundImage: AURORA_STARRY_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '200px 200px'
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-emerald-500 to-teal-500',
      sentText: 'text-slate-950 font-bold',
      receivedBg: 'bg-[#0d222e]',
      receivedText: 'text-teal-100',
      borderStyle: 'border border-teal-500/30',
      isSentDark: false,
      isReceivedDark: true,
      subtextSent: 'text-slate-950/70',
      subtextReceived: 'text-teal-400/60',
      linkSent: 'text-slate-950 underline',
      linkReceived: 'text-teal-300 underline'
    },
    previewGradient: 'from-[#05131a] to-[#0d222e]',
    badge: '🌌 Aurora',
    headerBg: 'bg-[#05131a]/90 backdrop-blur-md',
    headerBorder: 'border-b border-teal-900/60',
    headerText: 'text-teal-100',
    headerSubtext: 'text-teal-400',
    composerBg: 'bg-[#030d12]',
    composerBorder: 'border-t border-teal-900/60',
    innerInputBg: 'bg-[#0a1a24]',
    innerInputBorder: 'border-teal-800/60',
    innerInputText: 'text-teal-100',
    actionButtonText: 'text-teal-400',
    actionButtonHoverBg: 'hover:bg-teal-950/60',
    actionButtonActiveBg: 'bg-teal-900/60 text-teal-200',
    accentBg: 'bg-gradient-to-r from-emerald-400 to-teal-400 hover:brightness-110',
    accentText: 'text-slate-950 font-extrabold'
  },
  {
    id: 'sky_midnight_starlight',
    name: 'Midnight Starlight',
    category: 'sky',
    description: 'Deep obsidian night with sparkling silver stars and icy blue send button.',
    bgClass: 'bg-[#0b0f19] text-indigo-100',
    bgStyle: {
      backgroundColor: '#0b0f19',
      backgroundImage: STARS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '160px 160px'
    },
    bubble: {
      sentBg: 'bg-[#6366f1]',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-[#161f33]',
      receivedText: 'text-indigo-100',
      borderStyle: 'border border-indigo-500/30',
      isSentDark: true,
      isReceivedDark: true,
      subtextSent: 'text-indigo-200',
      subtextReceived: 'text-indigo-400/60',
      linkSent: 'text-white underline',
      linkReceived: 'text-indigo-300 underline'
    },
    previewGradient: 'from-[#0b0f19] to-[#161f33]',
    badge: '⭐ Starlight',
    headerBg: 'bg-[#0b0f19]/90 backdrop-blur-md',
    headerBorder: 'border-b border-indigo-900/60',
    headerText: 'text-indigo-100',
    headerSubtext: 'text-indigo-400',
    composerBg: 'bg-[#070a12]',
    composerBorder: 'border-t border-indigo-900/60',
    innerInputBg: 'bg-[#121929]',
    innerInputBorder: 'border-indigo-800/60',
    innerInputText: 'text-indigo-100',
    actionButtonText: 'text-indigo-400',
    actionButtonHoverBg: 'hover:bg-indigo-950/60',
    actionButtonActiveBg: 'bg-indigo-900/60 text-indigo-200',
    accentBg: 'bg-indigo-600 hover:bg-indigo-500',
    accentText: 'text-white font-bold'
  },
  {
    id: 'sky_pastel_twilight',
    name: 'Pastel Twilight Sky',
    category: 'sky',
    description: 'Dreamy lavender twilight sky with soft violet send controls.',
    bgClass: 'bg-[#f5f3ff] dark:bg-[#150d2a] text-purple-950 dark:text-purple-100',
    bgStyle: {
      backgroundImage: SKY_CLOUDS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '240px 240px'
    },
    bubble: {
      sentBg: 'bg-[#8b5cf6] dark:bg-[#a78bfa]',
      sentText: 'text-white dark:text-slate-950 font-bold',
      receivedBg: 'bg-white dark:bg-[#251744]',
      receivedText: 'text-purple-950 dark:text-purple-100',
      borderStyle: 'border border-purple-200 dark:border-purple-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-purple-100 dark:text-purple-950',
      subtextReceived: 'text-purple-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-purple-600 underline'
    },
    previewGradient: 'from-[#f5f3ff] to-[#ede9fe] dark:from-[#150d2a] to-[#291a4f]',
    badge: '🌆 Twilight Sky',
    headerBg: 'bg-[#f5f3ff]/90 dark:bg-[#150d2a]/90 backdrop-blur-md',
    headerBorder: 'border-b border-purple-200 dark:border-purple-900/50',
    headerText: 'text-purple-950 dark:text-purple-100',
    headerSubtext: 'text-purple-600 dark:text-purple-400',
    composerBg: 'bg-[#ede9fe]/60 dark:bg-[#0f091f]',
    composerBorder: 'border-t border-purple-200 dark:border-purple-900/50',
    innerInputBg: 'bg-white dark:bg-[#231542]',
    innerInputBorder: 'border-purple-300 dark:border-purple-800',
    innerInputText: 'text-purple-950 dark:text-purple-100',
    actionButtonText: 'text-purple-600 dark:text-purple-400',
    actionButtonHoverBg: 'hover:bg-purple-100 dark:hover:bg-purple-950/60',
    actionButtonActiveBg: 'bg-purple-200 dark:bg-purple-900 text-purple-800',
    accentBg: 'bg-purple-600 hover:bg-purple-500 dark:bg-purple-400 dark:hover:bg-purple-300',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'sky_nebula_deep_cosmos',
    name: 'Deep Nebula Cosmos',
    category: 'sky',
    description: 'Galactic deep nebula void with vibrant magenta/indigo cosmos send controls.',
    bgClass: 'bg-[#090514] text-purple-100',
    bgStyle: {
      backgroundColor: '#090514',
      backgroundImage: GALAXY_COSMOS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '240px 240px'
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-purple-600 to-pink-600',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-[#180f2d]',
      receivedText: 'text-purple-100',
      borderStyle: 'border border-purple-500/30',
      isSentDark: true,
      isReceivedDark: true,
      subtextSent: 'text-purple-200',
      subtextReceived: 'text-purple-400/60',
      linkSent: 'text-white underline',
      linkReceived: 'text-pink-300 underline'
    },
    previewGradient: 'from-[#090514] to-[#180f2d]',
    badge: '🌌 Deep Nebula',
    headerBg: 'bg-[#090514]/90 backdrop-blur-md',
    headerBorder: 'border-b border-purple-900/60',
    headerText: 'text-purple-100',
    headerSubtext: 'text-pink-400',
    composerBg: 'bg-[#06030e]',
    composerBorder: 'border-t border-purple-900/60',
    innerInputBg: 'bg-[#150c28]',
    innerInputBorder: 'border-purple-800/60',
    innerInputText: 'text-purple-100',
    actionButtonText: 'text-pink-400',
    actionButtonHoverBg: 'hover:bg-purple-950/60',
    actionButtonActiveBg: 'bg-purple-900/60 text-pink-200',
    accentBg: 'bg-gradient-to-r from-purple-600 to-pink-600 hover:brightness-110',
    accentText: 'text-white font-bold'
  },

  // ==================== 7. PROFESSIONAL & CORPORATE (37-42) ====================
  {
    id: 'professional_corporate_blue',
    name: 'Corporate Enterprise Slate',
    category: 'professional',
    description: 'Clean, trust-building enterprise slate blue for professional corporate teams.',
    bgClass: 'bg-[#f8fafc] dark:bg-[#0f172a] text-slate-900 dark:text-slate-100',
    bgStyle: {
      backgroundImage: PROFESSIONAL_TECH_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '64px 64px',
    },
    bubble: {
      sentBg: 'bg-[#1d4ed8] dark:bg-[#3b82f6]',
      sentText: 'text-white font-semibold',
      receivedBg: 'bg-white dark:bg-[#1e293b]',
      receivedText: 'text-slate-900 dark:text-slate-100',
      borderStyle: 'border border-slate-200 dark:border-slate-800',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-blue-100',
      subtextReceived: 'text-slate-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-blue-600 underline',
      cardBgSent: 'bg-black/15 text-white',
      cardBgReceived: 'bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100'
    },
    previewGradient: 'from-[#f8fafc] to-[#e2e8f0] dark:from-[#0f172a] to-[#1e293b]',
    badge: '🏢 Corporate',
    headerBg: 'bg-white/90 dark:bg-[#0f172a]/90 backdrop-blur-md',
    headerBorder: 'border-b border-slate-200 dark:border-slate-800',
    headerText: 'text-slate-900 dark:text-slate-50',
    headerSubtext: 'text-blue-600 dark:text-blue-400',
    composerBg: 'bg-[#f1f5f9] dark:bg-[#090d16]',
    composerBorder: 'border-t border-slate-200 dark:border-slate-800',
    innerInputBg: 'bg-white dark:bg-[#1a2332]',
    innerInputBorder: 'border-slate-300 dark:border-slate-700',
    innerInputText: 'text-slate-900 dark:text-slate-100',
    actionButtonText: 'text-blue-600 dark:text-blue-400',
    actionButtonHoverBg: 'hover:bg-blue-50 dark:hover:bg-blue-950/40',
    actionButtonActiveBg: 'bg-blue-100 dark:bg-blue-900/60 text-blue-700 dark:text-blue-300',
    accentBg: 'bg-blue-700 hover:bg-blue-800 dark:bg-blue-500 dark:hover:bg-blue-600',
    accentText: 'text-white font-semibold'
  },
  {
    id: 'professional_tech_blueprint',
    name: 'Technical Blueprint CAD',
    category: 'professional',
    description: 'Precision CAD grid & node blueprint background for software engineering teams.',
    bgClass: 'bg-[#0a1128] text-blue-100',
    bgStyle: {
      backgroundColor: '#0a1128',
      backgroundImage: PROFESSIONAL_TECH_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '64px 64px'
    },
    bubble: {
      sentBg: 'bg-[#0284c7]',
      sentText: 'text-white font-medium',
      receivedBg: 'bg-[#111c3a]',
      receivedText: 'text-blue-100',
      borderStyle: 'border border-cyan-500/30',
      isSentDark: true,
      isReceivedDark: true,
      subtextSent: 'text-cyan-100',
      subtextReceived: 'text-cyan-400/60',
      linkSent: 'text-white underline',
      linkReceived: 'text-cyan-300 underline'
    },
    previewGradient: 'from-[#0a1128] to-[#111c3a]',
    badge: '📐 Blueprint CAD',
    headerBg: 'bg-[#0a1128]/90 backdrop-blur-md',
    headerBorder: 'border-b border-blue-900/60',
    headerText: 'text-blue-100',
    headerSubtext: 'text-cyan-400',
    composerBg: 'bg-[#070d20]',
    composerBorder: 'border-t border-blue-900/60',
    innerInputBg: 'bg-[#131f40]',
    innerInputBorder: 'border-blue-800/60',
    innerInputText: 'text-blue-100',
    actionButtonText: 'text-cyan-400',
    actionButtonHoverBg: 'hover:bg-cyan-950/60',
    actionButtonActiveBg: 'bg-cyan-900/60 text-cyan-200',
    accentBg: 'bg-cyan-600 hover:bg-cyan-500',
    accentText: 'text-white font-bold'
  },
  {
    id: 'professional_executive_platinum',
    name: 'Executive Platinum',
    category: 'professional',
    description: 'Sophisticated monochromatic platinum steel for C-suite executive communications.',
    bgClass: 'bg-[#f1f5f9] dark:bg-[#0e1726] text-slate-900 dark:text-slate-100',
    bgStyle: {
      backgroundImage: CORPORATE_EXECUTIVE_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '40px 40px'
    },
    bubble: {
      sentBg: 'bg-[#334155] dark:bg-[#94a3b8]',
      sentText: 'text-white dark:text-slate-950 font-bold',
      receivedBg: 'bg-white dark:bg-[#1b2738]',
      receivedText: 'text-slate-900 dark:text-slate-100',
      borderStyle: 'border border-slate-300 dark:border-slate-800',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-slate-200 dark:text-slate-900',
      subtextReceived: 'text-slate-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-slate-700 underline'
    },
    previewGradient: 'from-[#f1f5f9] to-[#cbd5e1] dark:from-[#0e1726] to-[#1c2a3f]',
    badge: '💼 Executive',
    headerBg: 'bg-[#f1f5f9]/90 dark:bg-[#0e1726]/90 backdrop-blur-md',
    headerBorder: 'border-b border-slate-300 dark:border-slate-800',
    headerText: 'text-slate-900 dark:text-slate-100',
    headerSubtext: 'text-slate-600 dark:text-slate-400',
    composerBg: 'bg-[#e2e8f0] dark:bg-[#090f1a]',
    composerBorder: 'border-t border-slate-300 dark:border-slate-800',
    innerInputBg: 'bg-white dark:bg-[#1e2c40]',
    innerInputBorder: 'border-slate-300 dark:border-slate-700',
    innerInputText: 'text-slate-900 dark:text-slate-100',
    actionButtonText: 'text-slate-700 dark:text-slate-300',
    actionButtonHoverBg: 'hover:bg-slate-200 dark:hover:bg-slate-800',
    actionButtonActiveBg: 'bg-slate-300 dark:bg-slate-700 text-slate-900',
    accentBg: 'bg-slate-800 hover:bg-slate-900 dark:bg-slate-200 dark:hover:bg-white',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'professional_legal_charcoal',
    name: 'Legal Charcoal Minimal',
    category: 'professional',
    description: 'Authoritative deep charcoal slate designed for legal & advisory consultations.',
    bgClass: 'bg-[#111827] text-gray-100',
    bgStyle: {
      backgroundColor: '#111827',
      backgroundImage: PREMIUM_MINIMAL_LINEN,
      backgroundRepeat: 'repeat',
      backgroundSize: '30px 30px'
    },
    bubble: {
      sentBg: 'bg-[#374151]',
      sentText: 'text-white font-semibold',
      receivedBg: 'bg-[#1f2937]',
      receivedText: 'text-gray-100',
      borderStyle: 'border border-gray-700',
      isSentDark: true,
      isReceivedDark: true,
      subtextSent: 'text-gray-300',
      subtextReceived: 'text-gray-400/60',
      linkSent: 'text-white underline',
      linkReceived: 'text-gray-300 underline'
    },
    previewGradient: 'from-[#111827] to-[#1f2937]',
    badge: '⚖️ Legal Charcoal',
    headerBg: 'bg-[#111827]/90 backdrop-blur-md',
    headerBorder: 'border-b border-gray-800',
    headerText: 'text-gray-100',
    headerSubtext: 'text-gray-400',
    composerBg: 'bg-[#0d131f]',
    composerBorder: 'border-t border-gray-800',
    innerInputBg: 'bg-[#1f2937]',
    innerInputBorder: 'border-gray-700',
    innerInputText: 'text-gray-100',
    actionButtonText: 'text-gray-300',
    actionButtonHoverBg: 'hover:bg-gray-800',
    actionButtonActiveBg: 'bg-gray-700 text-white',
    accentBg: 'bg-gray-700 hover:bg-gray-600',
    accentText: 'text-white font-bold'
  },
  {
    id: 'professional_financial_navy',
    name: 'Financial Navy & Gold',
    category: 'professional',
    description: 'Wall Street navy blue background with investment gold controls.',
    bgClass: 'bg-[#0a192f] text-slate-100',
    bgStyle: {
      backgroundColor: '#0a192f',
      backgroundImage: CORPORATE_EXECUTIVE_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '40px 40px'
    },
    bubble: {
      sentBg: 'bg-[#d97706]',
      sentText: 'text-slate-950 font-bold',
      receivedBg: 'bg-[#112240]',
      receivedText: 'text-slate-100',
      borderStyle: 'border border-amber-500/30',
      isSentDark: false,
      isReceivedDark: true,
      subtextSent: 'text-slate-950/70',
      subtextReceived: 'text-amber-400/60',
      linkSent: 'text-slate-950 underline',
      linkReceived: 'text-amber-300 underline'
    },
    previewGradient: 'from-[#0a192f] to-[#112240]',
    badge: '📊 Financial Navy',
    headerBg: 'bg-[#0a192f]/90 backdrop-blur-md',
    headerBorder: 'border-b border-amber-500/20',
    headerText: 'text-slate-100',
    headerSubtext: 'text-amber-400',
    composerBg: 'bg-[#071325]',
    composerBorder: 'border-t border-amber-500/20',
    innerInputBg: 'bg-[#112240]',
    innerInputBorder: 'border-amber-500/30',
    innerInputText: 'text-slate-100',
    actionButtonText: 'text-amber-400',
    actionButtonHoverBg: 'hover:bg-amber-500/10',
    actionButtonActiveBg: 'bg-amber-500/20 text-amber-300',
    accentBg: 'bg-amber-600 hover:bg-amber-500',
    accentText: 'text-slate-950 font-extrabold'
  },
  {
    id: 'professional_studio_onyx',
    name: 'Creative Studio Onyx',
    category: 'professional',
    description: 'Sleek design studio dark slate with electric indigo accent controls.',
    bgClass: 'bg-[#0f1016] text-indigo-100',
    bgStyle: {
      backgroundColor: '#0f1016',
      backgroundImage: PROFESSIONAL_TECH_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '64px 64px'
    },
    bubble: {
      sentBg: 'bg-[#4f46e5]',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-[#181a24]',
      receivedText: 'text-indigo-100',
      borderStyle: 'border border-indigo-500/30',
      isSentDark: true,
      isReceivedDark: true,
      subtextSent: 'text-indigo-200',
      subtextReceived: 'text-indigo-400/60',
      linkSent: 'text-white underline',
      linkReceived: 'text-indigo-300 underline'
    },
    previewGradient: 'from-[#0f1016] to-[#181a24]',
    badge: '🎨 Studio Onyx',
    headerBg: 'bg-[#0f1016]/90 backdrop-blur-md',
    headerBorder: 'border-b border-indigo-900/60',
    headerText: 'text-indigo-100',
    headerSubtext: 'text-indigo-400',
    composerBg: 'bg-[#0a0b0f]',
    composerBorder: 'border-t border-indigo-900/60',
    innerInputBg: 'bg-[#1a1c28]',
    innerInputBorder: 'border-indigo-800/60',
    innerInputText: 'text-indigo-100',
    actionButtonText: 'text-indigo-400',
    actionButtonHoverBg: 'hover:bg-indigo-950/60',
    actionButtonActiveBg: 'bg-indigo-900/60 text-indigo-200',
    accentBg: 'bg-indigo-600 hover:bg-indigo-500',
    accentText: 'text-white font-bold'
  },

  // ==================== 8. FUN & VIBRANT (43-47) ====================
  {
    id: 'fun_cyberpunk_neon',
    name: 'Cyberpunk Neon Matrix',
    category: 'fun',
    description: 'Electric synthwave dark canvas with glowing neon magenta & cyan controls.',
    bgClass: 'bg-[#090814] text-pink-100',
    bgStyle: {
      backgroundColor: '#090814',
      backgroundImage: CYBERPUNK_GRID_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '60px 60px',
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-pink-600 to-rose-600',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-[#16122c]',
      receivedText: 'text-cyan-200',
      borderStyle: 'border border-pink-500/40',
      isSentDark: true,
      isReceivedDark: true,
      subtextSent: 'text-pink-200',
      subtextReceived: 'text-cyan-400/70',
      linkSent: 'text-white underline',
      linkReceived: 'text-pink-400 underline'
    },
    previewGradient: 'from-[#090814] to-[#16122c]',
    badge: '⚡ Cyberpunk',
    headerBg: 'bg-[#090814]/90 backdrop-blur-md',
    headerBorder: 'border-b border-pink-500/30',
    headerText: 'text-pink-100',
    headerSubtext: 'text-cyan-400',
    composerBg: 'bg-[#06050e]',
    composerBorder: 'border-t border-pink-500/30',
    innerInputBg: 'bg-[#181330]',
    innerInputBorder: 'border-pink-500/40',
    innerInputText: 'text-pink-100',
    actionButtonText: 'text-pink-400',
    actionButtonHoverBg: 'hover:bg-pink-950/60',
    actionButtonActiveBg: 'bg-pink-900/60 text-pink-200',
    accentBg: 'bg-gradient-to-r from-pink-500 to-cyan-500 hover:brightness-110',
    accentText: 'text-black font-extrabold'
  },
  {
    id: 'fun_retro_arcade_8bit',
    name: 'Retro Arcade 8-Bit',
    category: 'fun',
    description: 'Nostalgic 8-bit retro arcade background with bright arcade yellow send button.',
    bgClass: 'bg-[#120a2a] text-yellow-100',
    bgStyle: {
      backgroundColor: '#120a2a',
      backgroundImage: PIXEL_RETRO_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '32px 32px'
    },
    bubble: {
      sentBg: 'bg-[#eab308]',
      sentText: 'text-slate-950 font-black',
      receivedBg: 'bg-[#22134a]',
      receivedText: 'text-yellow-100',
      borderStyle: 'border border-yellow-500/40',
      isSentDark: false,
      isReceivedDark: true,
      subtextSent: 'text-slate-950/70',
      subtextReceived: 'text-yellow-400/60',
      linkSent: 'text-slate-950 underline',
      linkReceived: 'text-yellow-300 underline'
    },
    previewGradient: 'from-[#120a2a] to-[#22134a]',
    badge: '👾 8-Bit Arcade',
    headerBg: 'bg-[#120a2a]/90 backdrop-blur-md',
    headerBorder: 'border-b border-yellow-500/30',
    headerText: 'text-yellow-100',
    headerSubtext: 'text-yellow-400',
    composerBg: 'bg-[#0b061a]',
    composerBorder: 'border-t border-yellow-500/30',
    innerInputBg: 'bg-[#23144c]',
    innerInputBorder: 'border-yellow-500/40',
    innerInputText: 'text-yellow-100',
    actionButtonText: 'text-yellow-400',
    actionButtonHoverBg: 'hover:bg-yellow-950/60',
    actionButtonActiveBg: 'bg-yellow-900/60 text-yellow-200',
    accentBg: 'bg-yellow-500 hover:bg-yellow-400',
    accentText: 'text-slate-950 font-extrabold'
  },
  {
    id: 'fun_disco_sunset_glow',
    name: 'Disco Sunset Glow',
    category: 'fun',
    description: 'Hot neon coral & magenta disco glow with electric violet send button.',
    bgClass: 'bg-[#1f0318] text-rose-100',
    bgStyle: {
      backgroundColor: '#1f0318',
      backgroundImage: CYBERPUNK_GRID_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '60px 60px'
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-fuchsia-600 to-rose-600',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-[#36092b]',
      receivedText: 'text-rose-100',
      borderStyle: 'border border-fuchsia-500/30',
      isSentDark: true,
      isReceivedDark: true,
      subtextSent: 'text-rose-100',
      subtextReceived: 'text-rose-400/60',
      linkSent: 'text-white underline',
      linkReceived: 'text-fuchsia-300 underline'
    },
    previewGradient: 'from-[#1f0318] to-[#36092b]',
    badge: '🪩 Disco Glow',
    headerBg: 'bg-[#1f0318]/90 backdrop-blur-md',
    headerBorder: 'border-b border-fuchsia-900/60',
    headerText: 'text-rose-100',
    headerSubtext: 'text-fuchsia-400',
    composerBg: 'bg-[#150210]',
    composerBorder: 'border-t border-fuchsia-900/60',
    innerInputBg: 'bg-[#310727]',
    innerInputBorder: 'border-fuchsia-800/60',
    innerInputText: 'text-rose-100',
    actionButtonText: 'text-fuchsia-400',
    actionButtonHoverBg: 'hover:bg-fuchsia-950/60',
    actionButtonActiveBg: 'bg-fuchsia-900/60 text-fuchsia-200',
    accentBg: 'bg-gradient-to-r from-fuchsia-600 to-rose-600 hover:brightness-110',
    accentText: 'text-white font-bold'
  },
  {
    id: 'fun_vaporwave_sunset',
    name: 'Vaporwave Sunset Synth',
    category: 'fun',
    description: 'Retro 80s vaporwave pastel aesthetic with electric neon cyan send controls.',
    bgClass: 'bg-[#21002e] text-pink-100',
    bgStyle: {
      backgroundColor: '#21002e',
      backgroundImage: CYBERPUNK_GRID_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '60px 60px'
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-pink-500 via-purple-500 to-cyan-500',
      sentText: 'text-slate-950 font-extrabold',
      receivedBg: 'bg-[#3d0054]',
      receivedText: 'text-pink-100',
      borderStyle: 'border border-pink-500/30',
      isSentDark: false,
      isReceivedDark: true,
      subtextSent: 'text-slate-950/70',
      subtextReceived: 'text-pink-400/60',
      linkSent: 'text-slate-950 underline',
      linkReceived: 'text-cyan-300 underline'
    },
    previewGradient: 'from-[#21002e] to-[#3d0054]',
    badge: '🌴 Vaporwave',
    headerBg: 'bg-[#21002e]/90 backdrop-blur-md',
    headerBorder: 'border-b border-pink-900/60',
    headerText: 'text-pink-100',
    headerSubtext: 'text-cyan-400',
    composerBg: 'bg-[#15001e]',
    composerBorder: 'border-t border-pink-900/60',
    innerInputBg: 'bg-[#35004a]',
    innerInputBorder: 'border-pink-800/60',
    innerInputText: 'text-pink-100',
    actionButtonText: 'text-cyan-400',
    actionButtonHoverBg: 'hover:bg-pink-950/60',
    actionButtonActiveBg: 'bg-pink-900/60 text-cyan-200',
    accentBg: 'bg-gradient-to-r from-pink-500 via-purple-500 to-cyan-500 hover:brightness-110',
    accentText: 'text-slate-950 font-extrabold'
  },
  {
    id: 'fun_bubblegum_pop',
    name: 'Bubblegum Pop',
    category: 'fun',
    description: 'Vibrant pink & electric purple bubblegum pop theme with candy purple send controls.',
    bgClass: 'bg-[#fdf2f8] dark:bg-[#20081a] text-pink-950 dark:text-pink-100',
    bgStyle: {
      backgroundImage: SWEET_CANDY_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '220px 220px'
    },
    bubble: {
      sentBg: 'bg-[#d946ef] dark:bg-[#e879f9]',
      sentText: 'text-white dark:text-slate-950 font-bold',
      receivedBg: 'bg-white dark:bg-[#2d0c24]',
      receivedText: 'text-pink-950 dark:text-pink-100',
      borderStyle: 'border border-pink-200 dark:border-pink-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-pink-100 dark:text-pink-950',
      subtextReceived: 'text-pink-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-pink-600 underline'
    },
    previewGradient: 'from-[#fdf2f8] to-[#f5d0fe] dark:from-[#20081a] to-[#3a0f32]',
    badge: '🫧 Bubblegum Pop',
    headerBg: 'bg-[#fdf2f8]/90 dark:bg-[#20081a]/90 backdrop-blur-md',
    headerBorder: 'border-b border-pink-200 dark:border-pink-900/50',
    headerText: 'text-pink-950 dark:text-pink-100',
    headerSubtext: 'text-pink-600 dark:text-pink-400',
    composerBg: 'bg-[#f5d0fe]/60 dark:bg-[#160512]',
    composerBorder: 'border-t border-pink-200 dark:border-pink-900/50',
    innerInputBg: 'bg-white dark:bg-[#270b20]',
    innerInputBorder: 'border-pink-300 dark:border-pink-800',
    innerInputText: 'text-pink-950 dark:text-pink-100',
    actionButtonText: 'text-pink-600 dark:text-pink-400',
    actionButtonHoverBg: 'hover:bg-pink-100 dark:hover:bg-pink-950/60',
    actionButtonActiveBg: 'bg-pink-200 dark:bg-pink-900 text-pink-800',
    accentBg: 'bg-fuchsia-600 hover:bg-fuchsia-500 dark:bg-fuchsia-400 dark:hover:bg-fuchsia-300',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },

  // ==================== 9. CLASSIC MESSAGING (48-50) ====================
  {
    id: 'classic_whatsapp_emerald',
    name: 'WhatsApp Classic Emerald',
    category: 'classic',
    description: 'Authentic chat experience with signature green doodle wallpaper and emerald send controls.',
    bgClass: 'bg-[#efeae2] dark:bg-[#0b141a] text-[#111b21] dark:text-[#e9edef]',
    bgStyle: {
      backgroundImage: WHATSAPP_DOODLE,
      backgroundRepeat: 'repeat',
      backgroundSize: '160px 160px',
    },
    bubble: {
      sentBg: 'bg-[#d9fdd3] dark:bg-[#005c4b]',
      sentText: 'text-[#111b21] dark:text-[#e9edef]',
      receivedBg: 'bg-white dark:bg-[#202c33]',
      receivedText: 'text-[#111b21] dark:text-[#e9edef]',
      borderStyle: 'border border-[#e2dcd2] dark:border-[#007a64]/20',
      isSentDark: false,
      isReceivedDark: false,
      subtextSent: 'text-[#667781] dark:text-[#8696a0]',
      subtextReceived: 'text-[#667781] dark:text-[#8696a0]',
      linkSent: 'text-[#027eb5] dark:text-[#53bdeb] underline',
      linkReceived: 'text-[#027eb5] dark:text-[#53bdeb] underline',
    },
    previewGradient: 'from-[#efeae2] to-[#00a884]',
    badge: '💬 WhatsApp Classic',
    headerBg: 'bg-[#f0f2f5]/90 dark:bg-[#121b22]/90 backdrop-blur-md',
    headerBorder: 'border-b border-neutral-200 dark:border-[#222d34]',
    headerText: 'text-[#111b21] dark:text-[#e9edef]',
    headerSubtext: 'text-[#667781] dark:text-[#8696a0]',
    composerBg: 'bg-[#f0f2f5] dark:bg-[#0b141a]',
    composerBorder: 'border-t border-neutral-200 dark:border-[#222d34]',
    innerInputBg: 'bg-white dark:bg-[#2a3942]',
    innerInputBorder: 'border-neutral-200 dark:border-[#202c33]',
    innerInputText: 'text-[#111b21] dark:text-[#e9edef]',
    actionButtonText: 'text-[#00a884]',
    actionButtonHoverBg: 'hover:bg-[#005c4b]/20',
    actionButtonActiveBg: 'bg-[#005c4b] text-white',
    accentBg: 'bg-[#00a884] hover:bg-[#008f6f] dark:bg-[#005c4b] dark:hover:bg-[#007a64]',
    accentText: 'text-white font-bold'
  },
  {
    id: 'classic_imessage_clean',
    name: 'iMessage iOS Blue',
    category: 'classic',
    description: 'Clean iOS layout with iconic vibrant blue chat bubbles.',
    bgClass: 'bg-[#f2f2f7] dark:bg-[#000000] text-black dark:text-white',
    bgStyle: {
      backgroundImage: PREMIUM_MINIMAL_LINEN,
      backgroundRepeat: 'repeat',
      backgroundSize: '30px 30px'
    },
    bubble: {
      sentBg: 'bg-[#007aff]',
      sentText: 'text-white font-medium',
      receivedBg: 'bg-[#e5e5ea] dark:bg-[#26262a]',
      receivedText: 'text-black dark:text-white',
      borderStyle: 'border border-slate-200/50 dark:border-slate-800',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-blue-100',
      subtextReceived: 'text-neutral-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-[#007aff] underline'
    },
    previewGradient: 'from-[#f2f2f7] to-[#007aff]',
    badge: '📱 iMessage',
    headerBg: 'bg-[#f2f2f7]/90 dark:bg-[#000000]/90 backdrop-blur-md',
    headerBorder: 'border-b border-neutral-200 dark:border-neutral-800',
    headerText: 'text-black dark:text-white',
    headerSubtext: 'text-neutral-500 dark:text-neutral-400',
    composerBg: 'bg-[#f2f2f7] dark:bg-[#121212]',
    composerBorder: 'border-t border-neutral-200 dark:border-neutral-800',
    innerInputBg: 'bg-white dark:bg-[#1c1c1e]',
    innerInputBorder: 'border-neutral-300 dark:border-neutral-700',
    innerInputText: 'text-black dark:text-white',
    actionButtonText: 'text-[#007aff]',
    actionButtonHoverBg: 'hover:bg-blue-50 dark:hover:bg-blue-950/40',
    actionButtonActiveBg: 'bg-blue-100 dark:bg-blue-900 text-[#007aff]',
    accentBg: 'bg-[#007aff] hover:bg-blue-600',
    accentText: 'text-white font-bold'
  },
  {
    id: 'classic_telegram_dusk',
    name: 'Telegram Dusk Cyan',
    category: 'classic',
    description: 'Telegram dark blue dusk canvas with signature telegram cyan controls.',
    bgClass: 'bg-[#18222d] text-[#f5f5f5]',
    bgStyle: {
      backgroundColor: '#18222d',
      backgroundImage: STARS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '160px 160px'
    },
    bubble: {
      sentBg: 'bg-[#2b5278]',
      sentText: 'text-white font-medium',
      receivedBg: 'bg-[#212d3b]',
      receivedText: 'text-white',
      borderStyle: 'border border-[#2f3d4e]',
      isSentDark: true,
      isReceivedDark: true,
      subtextSent: 'text-[#7e9bb5]',
      subtextReceived: 'text-[#62768a]',
      linkSent: 'text-[#64b5f6] underline',
      linkReceived: 'text-[#64b5f6] underline'
    },
    previewGradient: 'from-[#18222d] to-[#212d3b]',
    badge: '✈️ Telegram Dusk',
    headerBg: 'bg-[#212d3b]/90 backdrop-blur-md',
    headerBorder: 'border-b border-[#141b22]',
    headerText: 'text-[#f5f5f5]',
    headerSubtext: 'text-[#7e9bb5]',
    composerBg: 'bg-[#18222d]',
    composerBorder: 'border-t border-[#141b22]',
    innerInputBg: 'bg-[#212d3b]',
    innerInputBorder: 'border-[#2f3d4e]',
    innerInputText: 'text-[#f5f5f5]',
    actionButtonText: 'text-[#64b5f6]',
    actionButtonHoverBg: 'hover:bg-[#2b5278]/40',
    actionButtonActiveBg: 'bg-[#2b5278] text-white',
    accentBg: 'bg-[#2b5278] hover:bg-[#32618e]',
    accentText: 'text-white font-bold'
  }
];
