import React from 'react';
import { 
  LEAVES_PATTERN, 
  STARS_PATTERN, 
  WHATSAPP_DOODLE, 
  ZENOA_AESTHETIC_MICRO_PATTERN,
  LOVE_ROMANCE_PATTERN,
  CUTE_ANIMALS_PATTERN,
  KIDS_WORLD_PATTERN,
  PREMIUM_MINIMAL_LINEN,
  PROFESSIONAL_TECH_PATTERN,
  DINO_ADVENTURE_PATTERN,
  SKY_CLOUDS_PATTERN,
  AURORA_STARRY_PATTERN,
  JUNGLE_BOTANICAL_PATTERN,
  CYBERPUNK_GRID_PATTERN,
  CORPORATE_EXECUTIVE_PATTERN,
  OCEAN_WAVES_PATTERN,
  SAKURA_BLOSSOM_PATTERN,
  PIXEL_RETRO_PATTERN,
  GALAXY_COSMOS_PATTERN,
  SWEET_CANDY_PATTERN
} from '../assets/wallpapers';

export interface ChatTheme {
  id: string;
  name: string;
  category: 'minimal' | 'love' | 'animals' | 'professional' | 'kids' | 'nature' | 'sky' | 'fun' | 'classic';
  description: string;
  bgClass: string;
  bgStyle?: React.CSSProperties;
  fontClass?: string;
  bubble: {
    sentBg: string;
    sentText: string;
    receivedBg: string;
    receivedText: string;
    borderStyle?: string;
    isSentDark?: boolean;
    isReceivedDark?: boolean;
    subtextSent?: string;
    subtextReceived?: string;
    linkSent?: string;
    linkReceived?: string;
    cardBgSent?: string;
    cardBgReceived?: string;
  };
  previewGradient: string;
  badge: string;
  
  headerBg: string;
  headerBorder: string;
  headerText: string;
  headerSubtext: string;
  composerBg: string;
  composerBorder: string;
  innerInputBg: string;
  innerInputBorder: string;
  innerInputText: string;

  actionButtonText: string;
  actionButtonHoverBg: string;
  actionButtonActiveBg: string;
  accentBg: string;
  accentText: string;
}

export const THEMES_PART1: ChatTheme[] = [
  // ==================== 1. MINIMAL & ZEN (1-6) ====================
  {
    id: 'minimal_clean_slate',
    name: 'Clean Slate',
    category: 'minimal',
    description: 'Crisp, eye-comforting neutral canvas with subtle aesthetic micro-motifs.',
    bgClass: 'bg-[#f8f9fa] dark:bg-[#0d1117] text-neutral-900 dark:text-neutral-100',
    bgStyle: {
      backgroundImage: ZENOA_AESTHETIC_MICRO_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '260px 260px',
    },
    bubble: {
      sentBg: 'bg-black dark:bg-[#e4e4e7]',
      sentText: 'text-white dark:text-black',
      receivedBg: 'bg-white dark:bg-[#18181b]',
      receivedText: 'text-neutral-900 dark:text-neutral-200',
      borderStyle: 'border border-neutral-200/60 dark:border-neutral-800',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-white/60 dark:text-black/60',
      subtextReceived: 'text-neutral-400 dark:text-neutral-500',
      linkSent: 'text-neutral-300 dark:text-neutral-700 underline font-semibold',
      linkReceived: 'text-blue-500 underline',
      cardBgSent: 'bg-white/10 dark:bg-black/10 border-white/20 dark:border-black/20 text-white dark:text-black',
      cardBgReceived: 'bg-neutral-50 dark:bg-neutral-800/50 border-neutral-200 dark:border-neutral-700 text-neutral-900 dark:text-neutral-100'
    },
    previewGradient: 'from-neutral-100 to-neutral-200 dark:from-neutral-900 dark:to-neutral-950',
    badge: '💎 Slate',
    headerBg: 'bg-white/90 dark:bg-[#0d1117]/90 backdrop-blur-md',
    headerBorder: 'border-b border-neutral-200/80 dark:border-neutral-800/80',
    headerText: 'text-neutral-900 dark:text-neutral-50',
    headerSubtext: 'text-neutral-500 dark:text-neutral-400',
    composerBg: 'bg-[#f8f9fa] dark:bg-[#0d1117]',
    composerBorder: 'border-t border-neutral-200/80 dark:border-neutral-800/80',
    innerInputBg: 'bg-white dark:bg-[#1c1c1e]',
    innerInputBorder: 'border-neutral-200 dark:border-neutral-800',
    innerInputText: 'text-neutral-900 dark:text-neutral-100',
    actionButtonText: 'text-indigo-600 dark:text-indigo-400',
    actionButtonHoverBg: 'hover:bg-indigo-50 dark:hover:bg-indigo-950/30',
    actionButtonActiveBg: 'bg-indigo-50 dark:bg-indigo-950/50 text-indigo-600 dark:text-indigo-400',
    accentBg: 'bg-indigo-600 hover:bg-indigo-700 dark:bg-indigo-500 dark:hover:bg-indigo-600',
    accentText: 'text-white'
  },
  {
    id: 'minimal_warm_linen',
    name: 'Warm Linen',
    category: 'minimal',
    description: 'Cozy, organic oatmeal backdrop with warm textile crosshatch pattern.',
    bgClass: 'bg-[#f7f4ee] dark:bg-[#151311] text-amber-950 dark:text-amber-50',
    bgStyle: {
      backgroundImage: PREMIUM_MINIMAL_LINEN,
      backgroundRepeat: 'repeat',
      backgroundSize: '30px 30px',
    },
    bubble: {
      sentBg: 'bg-[#4a3b32] dark:bg-[#d9c4b1]',
      sentText: 'text-[#fdfcfb] dark:text-[#1c120a]',
      receivedBg: 'bg-white dark:bg-[#201c18]',
      receivedText: 'text-neutral-800 dark:text-neutral-200',
      borderStyle: 'border border-[#e6decb] dark:border-[#382f25]',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-[#c2b0a3] dark:text-[#4d3826]',
      subtextReceived: 'text-neutral-400 dark:text-neutral-500',
      linkSent: 'text-[#f3e8ff] dark:text-[#6366f1] underline',
      linkReceived: 'text-[#854d0e] underline',
      cardBgSent: 'bg-black/15 dark:bg-white/10 text-white dark:text-black',
      cardBgReceived: 'bg-[#faf7f2] dark:bg-[#1a1714] text-neutral-900'
    },
    previewGradient: 'from-[#f7f4ee] to-[#e8decb] dark:from-[#151311] to-[#25201b]',
    badge: '🌾 Linen',
    headerBg: 'bg-[#fcfbf9]/90 dark:bg-[#151311]/90 backdrop-blur-md',
    headerBorder: 'border-b border-[#e6decb] dark:border-[#2a221a]',
    headerText: 'text-amber-950 dark:text-amber-100',
    headerSubtext: 'text-[#7a6a5e] dark:text-[#a09080]',
    composerBg: 'bg-[#faf8f5] dark:bg-[#1a1714]',
    composerBorder: 'border-t border-[#e6decb] dark:border-[#2a221a]',
    innerInputBg: 'bg-white dark:bg-[#201d1a]',
    innerInputBorder: 'border-[#dfd3bc] dark:border-[#382f25]',
    innerInputText: 'text-[#4a3b32] dark:text-[#e4d3c1]',
    actionButtonText: 'text-amber-800 dark:text-amber-300',
    actionButtonHoverBg: 'hover:bg-amber-100/80 dark:hover:bg-amber-950/40',
    actionButtonActiveBg: 'bg-amber-100 dark:bg-amber-950/50 text-amber-800 dark:text-amber-300',
    accentBg: 'bg-amber-800 hover:bg-amber-900 dark:bg-amber-600 dark:hover:bg-amber-700',
    accentText: 'text-[#fdfcfb] dark:text-[#1c120a]'
  },
  {
    id: 'minimal_sage_shadow',
    name: 'Sage Shadows',
    category: 'minimal',
    description: 'Deep resting sage tones with soft organic leaves pattern.',
    bgClass: 'bg-[#0f1412] text-emerald-50',
    bgStyle: {
      backgroundColor: '#0f1412',
      backgroundImage: LEAVES_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '120px 120px',
    },
    bubble: {
      sentBg: 'bg-[#1b3b2d]',
      sentText: 'text-[#e2f0e9]',
      receivedBg: 'bg-[#16221c]',
      receivedText: 'text-[#d3e4db]',
      borderStyle: 'border border-[#264436]',
      isSentDark: true,
      isReceivedDark: true,
      subtextSent: 'text-[#7ca993]',
      subtextReceived: 'text-[#6b9480]',
      linkSent: 'text-[#a7f3d0] underline',
      linkReceived: 'text-[#6ee7b7] underline'
    },
    previewGradient: 'from-[#0f1412] to-[#1b2922]',
    badge: '🌿 Sage',
    headerBg: 'bg-[#141c19]/90 backdrop-blur-md',
    headerBorder: 'border-b border-[#22352c]',
    headerText: 'text-[#e2f0e9]',
    headerSubtext: 'text-[#7ca993]',
    composerBg: 'bg-[#0f1412]',
    composerBorder: 'border-t border-[#22352c]',
    innerInputBg: 'bg-[#182620]',
    innerInputBorder: 'border-[#283e33]',
    innerInputText: 'text-[#e2f0e9]',
    actionButtonText: 'text-emerald-400',
    actionButtonHoverBg: 'hover:bg-emerald-950/50',
    actionButtonActiveBg: 'bg-emerald-900/60 text-emerald-300',
    accentBg: 'bg-emerald-600 hover:bg-emerald-500',
    accentText: 'text-white'
  },
  {
    id: 'minimal_obsidian_gold',
    name: 'Obsidian Gold',
    category: 'minimal',
    description: 'Ultra-luxurious dark canvas with warm metallic gold accents.',
    bgClass: 'bg-[#09090b] text-amber-100',
    bgStyle: {
      backgroundImage: CORPORATE_EXECUTIVE_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '40px 40px'
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-amber-600 to-yellow-600',
      sentText: 'text-black font-semibold',
      receivedBg: 'bg-[#18181b]',
      receivedText: 'text-amber-100',
      borderStyle: 'border border-amber-500/30',
      isSentDark: false,
      isReceivedDark: true,
      subtextSent: 'text-black/70',
      subtextReceived: 'text-amber-400/60',
      linkSent: 'text-black underline',
      linkReceived: 'text-amber-300 underline'
    },
    previewGradient: 'from-[#09090b] to-[#18181b]',
    badge: '👑 Obsidian Gold',
    headerBg: 'bg-[#09090b]/90 backdrop-blur-md',
    headerBorder: 'border-b border-amber-500/20',
    headerText: 'text-amber-200',
    headerSubtext: 'text-amber-500/70',
    composerBg: 'bg-[#09090b]',
    composerBorder: 'border-t border-amber-500/20',
    innerInputBg: 'bg-[#18181b]',
    innerInputBorder: 'border-amber-500/30',
    innerInputText: 'text-amber-100',
    actionButtonText: 'text-amber-400',
    actionButtonHoverBg: 'hover:bg-amber-500/10',
    actionButtonActiveBg: 'bg-amber-500/20 text-amber-300',
    accentBg: 'bg-gradient-to-r from-amber-500 to-yellow-500 hover:brightness-110',
    accentText: 'text-black font-extrabold'
  },
  {
    id: 'minimal_soft_cream',
    name: 'Soft Pearl Cream',
    category: 'minimal',
    description: 'Serene milk pearl aesthetic with soft velvet highlights.',
    bgClass: 'bg-[#faf8f5] dark:bg-[#121110] text-stone-900 dark:text-stone-100',
    bgStyle: {
      backgroundImage: ZENOA_AESTHETIC_MICRO_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '240px 240px'
    },
    bubble: {
      sentBg: 'bg-[#292524] dark:bg-[#e7e5e4]',
      sentText: 'text-[#fafaf9] dark:text-[#1c1917]',
      receivedBg: 'bg-white dark:bg-[#1c1917]',
      receivedText: 'text-stone-800 dark:text-stone-200',
      borderStyle: 'border border-stone-200 dark:border-stone-800',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-stone-400 dark:text-stone-600',
      subtextReceived: 'text-stone-400 dark:text-stone-500',
      linkSent: 'text-stone-200 dark:text-stone-800 underline',
      linkReceived: 'text-amber-700 underline'
    },
    previewGradient: 'from-[#faf8f5] to-[#f0ece1] dark:from-[#121110] to-[#201d1b]',
    badge: '🕊️ Pearl Cream',
    headerBg: 'bg-[#faf8f5]/90 dark:bg-[#121110]/90 backdrop-blur-md',
    headerBorder: 'border-b border-stone-200 dark:border-stone-800',
    headerText: 'text-stone-900 dark:text-stone-100',
    headerSubtext: 'text-stone-500 dark:text-stone-400',
    composerBg: 'bg-[#f5f2eb] dark:bg-[#181615]',
    composerBorder: 'border-t border-stone-200 dark:border-stone-800',
    innerInputBg: 'bg-white dark:bg-[#211e1c]',
    innerInputBorder: 'border-stone-300 dark:border-stone-700',
    innerInputText: 'text-stone-900 dark:text-stone-100',
    actionButtonText: 'text-stone-700 dark:text-stone-300',
    actionButtonHoverBg: 'hover:bg-stone-200/60 dark:hover:bg-stone-800/60',
    actionButtonActiveBg: 'bg-stone-200 dark:bg-stone-800 text-stone-900',
    accentBg: 'bg-stone-800 hover:bg-stone-900 dark:bg-stone-200 dark:hover:bg-white',
    accentText: 'text-white dark:text-stone-900 font-bold'
  },
  {
    id: 'minimal_nordic_snow',
    name: 'Nordic Snow',
    category: 'minimal',
    description: 'Crisp arctic snow white background with cool slate teal buttons.',
    bgClass: 'bg-[#f0f9ff] dark:bg-[#0c1929] text-slate-900 dark:text-slate-100',
    bgStyle: {
      backgroundImage: PREMIUM_MINIMAL_LINEN,
      backgroundRepeat: 'repeat',
      backgroundSize: '32px 32px'
    },
    bubble: {
      sentBg: 'bg-[#0284c7] dark:bg-[#38bdf8]',
      sentText: 'text-white dark:text-slate-950 font-medium',
      receivedBg: 'bg-white dark:bg-[#15273b]',
      receivedText: 'text-slate-800 dark:text-slate-200',
      borderStyle: 'border border-sky-200 dark:border-sky-900/40',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-sky-100 dark:text-slate-900',
      subtextReceived: 'text-slate-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-sky-600 underline'
    },
    previewGradient: 'from-[#f0f9ff] to-[#e0f2fe] dark:from-[#0c1929] to-[#172e48]',
    badge: '❄️ Nordic Snow',
    headerBg: 'bg-[#f0f9ff]/90 dark:bg-[#0c1929]/90 backdrop-blur-md',
    headerBorder: 'border-b border-sky-100 dark:border-sky-900/50',
    headerText: 'text-slate-900 dark:text-slate-50',
    headerSubtext: 'text-sky-600 dark:text-sky-400',
    composerBg: 'bg-[#e0f2fe]/60 dark:bg-[#0a1523]',
    composerBorder: 'border-t border-sky-200 dark:border-sky-900/50',
    innerInputBg: 'bg-white dark:bg-[#132337]',
    innerInputBorder: 'border-sky-200 dark:border-sky-800',
    innerInputText: 'text-slate-900 dark:text-slate-100',
    actionButtonText: 'text-sky-600 dark:text-sky-400',
    actionButtonHoverBg: 'hover:bg-sky-100 dark:hover:bg-sky-950/50',
    actionButtonActiveBg: 'bg-sky-200 dark:bg-sky-900 text-sky-800',
    accentBg: 'bg-sky-600 hover:bg-sky-500 dark:bg-sky-400 dark:hover:bg-sky-300',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },

  // ==================== 2. LOVE & HEARTS (7-12) ====================
  {
    id: 'love_crimson_passion',
    name: 'Crimson Romance',
    category: 'love',
    description: 'Enchanting romance backdrop with scattered hearts and crimson send button.',
    bgClass: 'bg-[#2b0812] text-rose-100',
    bgStyle: {
      backgroundColor: '#2b0812',
      backgroundImage: LOVE_ROMANCE_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '260px 260px',
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-rose-600 to-pink-600',
      sentText: 'text-white font-medium',
      receivedBg: 'bg-[#42101e]',
      receivedText: 'text-rose-100',
      borderStyle: 'border border-rose-500/30',
      isSentDark: true,
      isReceivedDark: true,
      subtextSent: 'text-rose-200/80',
      subtextReceived: 'text-rose-300/60',
      linkSent: 'text-white underline',
      linkReceived: 'text-rose-300 underline'
    },
    previewGradient: 'from-[#2b0812] to-[#42101e]',
    badge: '❤️ Crimson',
    headerBg: 'bg-[#23060e]/90 backdrop-blur-md',
    headerBorder: 'border-b border-rose-900/60',
    headerText: 'text-rose-100',
    headerSubtext: 'text-rose-400',
    composerBg: 'bg-[#21050d]',
    composerBorder: 'border-t border-rose-900/60',
    innerInputBg: 'bg-[#3b0d1a]',
    innerInputBorder: 'border-rose-800/60',
    innerInputText: 'text-rose-100',
    actionButtonText: 'text-rose-400',
    actionButtonHoverBg: 'hover:bg-rose-950/60',
    actionButtonActiveBg: 'bg-rose-900/60 text-rose-200',
    accentBg: 'bg-gradient-to-r from-rose-600 to-pink-600 hover:from-rose-500 hover:to-pink-500',
    accentText: 'text-white font-bold'
  },
  {
    id: 'love_sweet_blossom',
    name: 'Sweet Pink Blossom',
    category: 'love',
    description: 'Soft pastel pink aesthetic with floating hearts and blush send controls.',
    bgClass: 'bg-[#fff1f2] dark:bg-[#200a12] text-rose-950 dark:text-rose-100',
    bgStyle: {
      backgroundImage: LOVE_ROMANCE_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '240px 240px'
    },
    bubble: {
      sentBg: 'bg-[#f43f5e] dark:bg-[#fb7185]',
      sentText: 'text-white dark:text-slate-950 font-medium',
      receivedBg: 'bg-white dark:bg-[#2e121c]',
      receivedText: 'text-rose-900 dark:text-rose-100',
      borderStyle: 'border border-rose-200 dark:border-rose-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-rose-100 dark:text-rose-950',
      subtextReceived: 'text-rose-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-rose-600 underline'
    },
    previewGradient: 'from-[#fff1f2] to-[#fecdd3] dark:from-[#200a12] to-[#3b1220]',
    badge: '🌸 Sweet Pink',
    headerBg: 'bg-[#fff1f2]/90 dark:bg-[#200a12]/90 backdrop-blur-md',
    headerBorder: 'border-b border-rose-200 dark:border-rose-900/50',
    headerText: 'text-rose-900 dark:text-rose-100',
    headerSubtext: 'text-rose-500 dark:text-rose-400',
    composerBg: 'bg-[#ffe4e6] dark:bg-[#1a070e]',
    composerBorder: 'border-t border-rose-200 dark:border-rose-900/50',
    innerInputBg: 'bg-white dark:bg-[#2d111b]',
    innerInputBorder: 'border-rose-300 dark:border-rose-800',
    innerInputText: 'text-rose-900 dark:text-rose-100',
    actionButtonText: 'text-rose-600 dark:text-rose-400',
    actionButtonHoverBg: 'hover:bg-rose-100 dark:hover:bg-rose-950/60',
    actionButtonActiveBg: 'bg-rose-200 dark:bg-rose-900 text-rose-800',
    accentBg: 'bg-rose-500 hover:bg-rose-600 dark:bg-rose-400 dark:hover:bg-rose-500',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'love_rose_gold_luxe',
    name: 'Rose Gold Luxury',
    category: 'love',
    description: 'Sophisticated champagne gold background with rose gold controls.',
    bgClass: 'bg-[#faf0e6] dark:bg-[#1d1616] text-amber-950 dark:text-amber-100',
    bgStyle: {
      backgroundImage: SAKURA_BLOSSOM_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '200px 200px'
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-[#e0a96d] to-[#d4af37]',
      sentText: 'text-slate-950 font-bold',
      receivedBg: 'bg-white dark:bg-[#2a2121]',
      receivedText: 'text-stone-800 dark:text-stone-100',
      borderStyle: 'border border-amber-300/60 dark:border-amber-900/40',
      isSentDark: false,
      isReceivedDark: false,
      subtextSent: 'text-slate-800/80',
      subtextReceived: 'text-amber-700/60',
      linkSent: 'text-slate-950 underline',
      linkReceived: 'text-amber-800 underline'
    },
    previewGradient: 'from-[#faf0e6] to-[#eddcd2] dark:from-[#1d1616] to-[#2c2222]',
    badge: '✨ Rose Gold',
    headerBg: 'bg-[#faf0e6]/90 dark:bg-[#1d1616]/90 backdrop-blur-md',
    headerBorder: 'border-b border-amber-200 dark:border-amber-900/40',
    headerText: 'text-stone-900 dark:text-stone-100',
    headerSubtext: 'text-amber-700 dark:text-amber-400',
    composerBg: 'bg-[#f5e5d6] dark:bg-[#171111]',
    composerBorder: 'border-t border-amber-200 dark:border-amber-900/40',
    innerInputBg: 'bg-white dark:bg-[#281f1f]',
    innerInputBorder: 'border-amber-300 dark:border-amber-800',
    innerInputText: 'text-stone-900 dark:text-stone-100',
    actionButtonText: 'text-amber-700 dark:text-amber-400',
    actionButtonHoverBg: 'hover:bg-amber-100 dark:hover:bg-amber-950/50',
    actionButtonActiveBg: 'bg-amber-200 dark:bg-amber-900 text-amber-900',
    accentBg: 'bg-gradient-to-r from-[#d4af37] to-[#e0a96d] hover:brightness-105',
    accentText: 'text-slate-950 font-extrabold'
  },
  {
    id: 'love_lavender_kiss',
    name: 'Lavender Kiss',
    category: 'love',
    description: 'Dreamy lilac lavender background with deep purple romantic send controls.',
    bgClass: 'bg-[#f3e8ff] dark:bg-[#180d28] text-purple-950 dark:text-purple-100',
    bgStyle: {
      backgroundImage: LOVE_ROMANCE_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '250px 250px'
    },
    bubble: {
      sentBg: 'bg-[#9333ea] dark:bg-[#c084fc]',
      sentText: 'text-white dark:text-slate-950 font-medium',
      receivedBg: 'bg-white dark:bg-[#28173e]',
      receivedText: 'text-purple-950 dark:text-purple-100',
      borderStyle: 'border border-purple-200 dark:border-purple-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-purple-100 dark:text-purple-950',
      subtextReceived: 'text-purple-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-purple-600 underline'
    },
    previewGradient: 'from-[#f3e8ff] to-[#e9d5ff] dark:from-[#180d28] to-[#2e174b]',
    badge: '💜 Lavender',
    headerBg: 'bg-[#f3e8ff]/90 dark:bg-[#180d28]/90 backdrop-blur-md',
    headerBorder: 'border-b border-purple-200 dark:border-purple-900/50',
    headerText: 'text-purple-950 dark:text-purple-100',
    headerSubtext: 'text-purple-600 dark:text-purple-400',
    composerBg: 'bg-[#e9d5ff]/60 dark:bg-[#120920]',
    composerBorder: 'border-t border-purple-200 dark:border-purple-900/50',
    innerInputBg: 'bg-white dark:bg-[#25133b]',
    innerInputBorder: 'border-purple-300 dark:border-purple-800',
    innerInputText: 'text-purple-950 dark:text-purple-100',
    actionButtonText: 'text-purple-600 dark:text-purple-400',
    actionButtonHoverBg: 'hover:bg-purple-100 dark:hover:bg-purple-950/60',
    actionButtonActiveBg: 'bg-purple-200 dark:bg-purple-900 text-purple-800',
    accentBg: 'bg-purple-600 hover:bg-purple-500 dark:bg-purple-400 dark:hover:bg-purple-300',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'love_sunset_romance',
    name: 'Sunset Romance',
    category: 'love',
    description: 'Warm peach sunset theme with coral romantic send button.',
    bgClass: 'bg-[#fff7ed] dark:bg-[#2a1208] text-amber-950 dark:text-amber-100',
    bgStyle: {
      backgroundImage: LOVE_ROMANCE_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '240px 240px'
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-orange-500 to-amber-500',
      sentText: 'text-white font-medium',
      receivedBg: 'bg-white dark:bg-[#381a0e]',
      receivedText: 'text-amber-950 dark:text-amber-100',
      borderStyle: 'border border-orange-200 dark:border-orange-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-orange-100',
      subtextReceived: 'text-orange-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-orange-600 underline'
    },
    previewGradient: 'from-[#fff7ed] to-[#ffedd5] dark:from-[#2a1208] to-[#421d0d]',
    badge: '🌅 Sunset Love',
    headerBg: 'bg-[#fff7ed]/90 dark:bg-[#2a1208]/90 backdrop-blur-md',
    headerBorder: 'border-b border-orange-200 dark:border-orange-900/50',
    headerText: 'text-orange-950 dark:text-orange-100',
    headerSubtext: 'text-orange-600 dark:text-orange-400',
    composerBg: 'bg-[#ffedd5]/60 dark:bg-[#200c05]',
    composerBorder: 'border-t border-orange-200 dark:border-orange-900/50',
    innerInputBg: 'bg-white dark:bg-[#33170c]',
    innerInputBorder: 'border-orange-300 dark:border-orange-800',
    innerInputText: 'text-amber-950 dark:text-amber-100',
    actionButtonText: 'text-orange-600 dark:text-orange-400',
    actionButtonHoverBg: 'hover:bg-orange-100 dark:hover:bg-orange-950/60',
    actionButtonActiveBg: 'bg-orange-200 dark:bg-orange-900 text-orange-800',
    accentBg: 'bg-gradient-to-r from-orange-500 to-amber-500 hover:brightness-110',
    accentText: 'text-white font-bold'
  },
  {
    id: 'love_midnight_heartbeat',
    name: 'Midnight Heartbeat',
    category: 'love',
    description: 'Dramatic black canvas with vibrant crimson glowing heartbeat buttons.',
    bgClass: 'bg-[#0a0507] text-rose-100',
    bgStyle: {
      backgroundColor: '#0a0507',
      backgroundImage: LOVE_ROMANCE_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '240px 240px'
    },
    bubble: {
      sentBg: 'bg-red-600',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-[#180b10]',
      receivedText: 'text-rose-100',
      borderStyle: 'border border-red-500/30',
      isSentDark: true,
      isReceivedDark: true,
      subtextSent: 'text-red-200',
      subtextReceived: 'text-red-400/60',
      linkSent: 'text-white underline',
      linkReceived: 'text-red-400 underline'
    },
    previewGradient: 'from-[#0a0507] to-[#1a080f]',
    badge: '💓 Heartbeat',
    headerBg: 'bg-[#0a0507]/90 backdrop-blur-md',
    headerBorder: 'border-b border-red-900/50',
    headerText: 'text-rose-100',
    headerSubtext: 'text-red-400',
    composerBg: 'bg-[#080305]',
    composerBorder: 'border-t border-red-900/50',
    innerInputBg: 'bg-[#18080f]',
    innerInputBorder: 'border-red-800/50',
    innerInputText: 'text-rose-100',
    actionButtonText: 'text-red-400',
    actionButtonHoverBg: 'hover:bg-red-950/60',
    actionButtonActiveBg: 'bg-red-900/60 text-red-200',
    accentBg: 'bg-red-600 hover:bg-red-500',
    accentText: 'text-white font-extrabold'
  },

  // ==================== 3. CUTE ANIMALS (13-18) ====================
  {
    id: 'animals_kitty_whiskers',
    name: 'Kitty Whiskers',
    category: 'animals',
    description: 'Playful kitty paws & whiskers pattern with warm coral orange controls.',
    bgClass: 'bg-[#fff8f0] dark:bg-[#1a120b] text-amber-950 dark:text-amber-100',
    bgStyle: {
      backgroundImage: CUTE_ANIMALS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '280px 280px',
    },
    bubble: {
      sentBg: 'bg-[#f97316] dark:bg-[#fb923c]',
      sentText: 'text-white dark:text-slate-950 font-medium',
      receivedBg: 'bg-white dark:bg-[#281c12]',
      receivedText: 'text-amber-950 dark:text-amber-100',
      borderStyle: 'border border-amber-200 dark:border-amber-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-orange-100 dark:text-orange-950',
      subtextReceived: 'text-amber-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-orange-600 underline'
    },
    previewGradient: 'from-[#fff8f0] to-[#ffedd5] dark:from-[#1a120b] to-[#2e1d10]',
    badge: '🐱 Kitty',
    headerBg: 'bg-[#fff8f0]/90 dark:bg-[#1a120b]/90 backdrop-blur-md',
    headerBorder: 'border-b border-orange-200 dark:border-orange-900/50',
    headerText: 'text-amber-950 dark:text-amber-100',
    headerSubtext: 'text-orange-600 dark:text-orange-400',
    composerBg: 'bg-[#ffedd5]/60 dark:bg-[#130d07]',
    composerBorder: 'border-t border-orange-200 dark:border-orange-900/50',
    innerInputBg: 'bg-white dark:bg-[#26190e]',
    innerInputBorder: 'border-orange-300 dark:border-orange-800',
    innerInputText: 'text-amber-950 dark:text-amber-100',
    actionButtonText: 'text-orange-600 dark:text-orange-400',
    actionButtonHoverBg: 'hover:bg-orange-100 dark:hover:bg-orange-950/60',
    actionButtonActiveBg: 'bg-orange-200 dark:bg-orange-900 text-orange-800',
    accentBg: 'bg-orange-500 hover:bg-orange-600 dark:bg-orange-400 dark:hover:bg-orange-500',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'animals_puppy_paws',
    name: 'Puppy Paws',
    category: 'animals',
    description: 'Adorable puppy bone & paw prints with cozy caramel controls.',
    bgClass: 'bg-[#faf4ed] dark:bg-[#18130e] text-stone-900 dark:text-stone-100',
    bgStyle: {
      backgroundImage: CUTE_ANIMALS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '260px 260px'
    },
    bubble: {
      sentBg: 'bg-[#854d0e] dark:bg-[#ca8a04]',
      sentText: 'text-white dark:text-slate-950 font-bold',
      receivedBg: 'bg-white dark:bg-[#251e17]',
      receivedText: 'text-stone-900 dark:text-stone-100',
      borderStyle: 'border border-amber-300 dark:border-amber-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-amber-100 dark:text-amber-950',
      subtextReceived: 'text-amber-500',
      linkSent: 'text-white underline',
      linkReceived: 'text-amber-700 underline'
    },
    previewGradient: 'from-[#faf4ed] to-[#f0e4d7] dark:from-[#18130e] to-[#282017]',
    badge: '🐶 Puppy Paws',
    headerBg: 'bg-[#faf4ed]/90 dark:bg-[#18130e]/90 backdrop-blur-md',
    headerBorder: 'border-b border-amber-200 dark:border-amber-900/50',
    headerText: 'text-stone-900 dark:text-stone-100',
    headerSubtext: 'text-amber-700 dark:text-amber-400',
    composerBg: 'bg-[#f5e9dc] dark:bg-[#120e0a]',
    composerBorder: 'border-t border-amber-200 dark:border-amber-900/50',
    innerInputBg: 'bg-white dark:bg-[#221b14]',
    innerInputBorder: 'border-amber-300 dark:border-amber-800',
    innerInputText: 'text-stone-900 dark:text-stone-100',
    actionButtonText: 'text-amber-800 dark:text-amber-400',
    actionButtonHoverBg: 'hover:bg-amber-100 dark:hover:bg-amber-950/50',
    actionButtonActiveBg: 'bg-amber-200 dark:bg-amber-900 text-amber-900',
    accentBg: 'bg-amber-700 hover:bg-amber-800 dark:bg-amber-500 dark:hover:bg-amber-400',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'animals_shiba_inu',
    name: 'Shiba Inu Sunburst',
    category: 'animals',
    description: 'Golden Japanese Shiba Inu theme with sunburst yellow send controls.',
    bgClass: 'bg-[#fefce8] dark:bg-[#1d1a08] text-amber-950 dark:text-amber-100',
    bgStyle: {
      backgroundImage: CUTE_ANIMALS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '270px 270px'
    },
    bubble: {
      sentBg: 'bg-[#eab308] dark:bg-[#facc15]',
      sentText: 'text-slate-950 font-extrabold',
      receivedBg: 'bg-white dark:bg-[#2b2710]',
      receivedText: 'text-amber-950 dark:text-amber-100',
      borderStyle: 'border border-yellow-300 dark:border-yellow-900/50',
      isSentDark: false,
      isReceivedDark: false,
      subtextSent: 'text-slate-950/70',
      subtextReceived: 'text-amber-500',
      linkSent: 'text-slate-950 underline',
      linkReceived: 'text-yellow-700 underline'
    },
    previewGradient: 'from-[#fefce8] to-[#fef08a] dark:from-[#1d1a08] to-[#302c10]',
    badge: '🐕 Shiba Inu',
    headerBg: 'bg-[#fefce8]/90 dark:bg-[#1d1a08]/90 backdrop-blur-md',
    headerBorder: 'border-b border-yellow-200 dark:border-yellow-900/50',
    headerText: 'text-amber-950 dark:text-amber-100',
    headerSubtext: 'text-yellow-700 dark:text-yellow-400',
    composerBg: 'bg-[#fef9c3]/60 dark:bg-[#151305]',
    composerBorder: 'border-t border-yellow-200 dark:border-yellow-900/50',
    innerInputBg: 'bg-white dark:bg-[#28240f]',
    innerInputBorder: 'border-yellow-300 dark:border-yellow-800',
    innerInputText: 'text-amber-950 dark:text-amber-100',
    actionButtonText: 'text-yellow-700 dark:text-yellow-400',
    actionButtonHoverBg: 'hover:bg-yellow-100 dark:hover:bg-yellow-950/50',
    actionButtonActiveBg: 'bg-yellow-200 dark:bg-yellow-900 text-yellow-900',
    accentBg: 'bg-yellow-500 hover:bg-yellow-600 dark:bg-yellow-400 dark:hover:bg-yellow-300',
    accentText: 'text-slate-950 font-extrabold'
  },
  {
    id: 'animals_panda_bamboo',
    name: 'Panda Garden',
    category: 'animals',
    description: 'Clean monochrome panda theme with fresh bamboo emerald buttons.',
    bgClass: 'bg-[#f8fafc] dark:bg-[#0b1311] text-emerald-950 dark:text-emerald-50',
    bgStyle: {
      backgroundImage: JUNGLE_BOTANICAL_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '220px 220px'
    },
    bubble: {
      sentBg: 'bg-[#059669] dark:bg-[#10b981]',
      sentText: 'text-white dark:text-slate-950 font-bold',
      receivedBg: 'bg-white dark:bg-[#15221e]',
      receivedText: 'text-emerald-950 dark:text-emerald-100',
      borderStyle: 'border border-emerald-200 dark:border-emerald-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-emerald-100 dark:text-emerald-950',
      subtextReceived: 'text-emerald-500',
      linkSent: 'text-white underline',
      linkReceived: 'text-emerald-600 underline'
    },
    previewGradient: 'from-[#f8fafc] to-[#e2e8f0] dark:from-[#0b1311] to-[#14231f]',
    badge: '🐼 Panda Bamboo',
    headerBg: 'bg-[#f8fafc]/90 dark:bg-[#0b1311]/90 backdrop-blur-md',
    headerBorder: 'border-b border-emerald-200 dark:border-emerald-900/50',
    headerText: 'text-emerald-950 dark:text-emerald-50',
    headerSubtext: 'text-emerald-600 dark:text-emerald-400',
    composerBg: 'bg-[#f1f5f9] dark:bg-[#080e0c]',
    composerBorder: 'border-t border-emerald-200 dark:border-emerald-900/50',
    innerInputBg: 'bg-white dark:bg-[#182924]',
    innerInputBorder: 'border-emerald-300 dark:border-emerald-800',
    innerInputText: 'text-emerald-950 dark:text-emerald-50',
    actionButtonText: 'text-emerald-600 dark:text-emerald-400',
    actionButtonHoverBg: 'hover:bg-emerald-100 dark:hover:bg-emerald-950/60',
    actionButtonActiveBg: 'bg-emerald-200 dark:bg-emerald-900 text-emerald-800',
    accentBg: 'bg-emerald-600 hover:bg-emerald-500 dark:bg-emerald-400 dark:hover:bg-emerald-300',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'animals_bunny_hop',
    name: 'Bunny Hop Marshmallow',
    category: 'animals',
    description: 'Soft pink marshmallow aesthetic with cute bunny hop send controls.',
    bgClass: 'bg-[#fdf2f8] dark:bg-[#200a16] text-pink-950 dark:text-pink-100',
    bgStyle: {
      backgroundImage: CUTE_ANIMALS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '250px 250px'
    },
    bubble: {
      sentBg: 'bg-[#ec4899] dark:bg-[#f472b6]',
      sentText: 'text-white dark:text-slate-950 font-medium',
      receivedBg: 'bg-white dark:bg-[#2e1122]',
      receivedText: 'text-pink-950 dark:text-pink-100',
      borderStyle: 'border border-pink-200 dark:border-pink-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-pink-100 dark:text-pink-950',
      subtextReceived: 'text-pink-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-pink-600 underline'
    },
    previewGradient: 'from-[#fdf2f8] to-[#fce7f3] dark:from-[#200a16] to-[#361127]',
    badge: '🐰 Bunny Hop',
    headerBg: 'bg-[#fdf2f8]/90 dark:bg-[#200a16]/90 backdrop-blur-md',
    headerBorder: 'border-b border-pink-200 dark:border-pink-900/50',
    headerText: 'text-pink-950 dark:text-pink-100',
    headerSubtext: 'text-pink-600 dark:text-pink-400',
    composerBg: 'bg-[#fce7f3]/60 dark:bg-[#180710]',
    composerBorder: 'border-t border-pink-200 dark:border-pink-900/50',
    innerInputBg: 'bg-white dark:bg-[#2a1020]',
    innerInputBorder: 'border-pink-300 dark:border-pink-800',
    innerInputText: 'text-pink-950 dark:text-pink-100',
    actionButtonText: 'text-pink-600 dark:text-pink-400',
    actionButtonHoverBg: 'hover:bg-pink-100 dark:hover:bg-pink-950/60',
    actionButtonActiveBg: 'bg-pink-200 dark:bg-pink-900 text-pink-800',
    accentBg: 'bg-pink-500 hover:bg-pink-600 dark:bg-pink-400 dark:hover:bg-pink-500',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'animals_wild_safari',
    name: 'Wild Safari Savanna',
    category: 'animals',
    description: 'Golden African savanna theme with warm amber safari controls.',
    bgClass: 'bg-[#fef3c7] dark:bg-[#201705] text-amber-950 dark:text-amber-100',
    bgStyle: {
      backgroundImage: CUTE_ANIMALS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '280px 280px'
    },
    bubble: {
      sentBg: 'bg-[#d97706] dark:bg-[#f59e0b]',
      sentText: 'text-white dark:text-slate-950 font-bold',
      receivedBg: 'bg-white dark:bg-[#2e220a]',
      receivedText: 'text-amber-950 dark:text-amber-100',
      borderStyle: 'border border-amber-300 dark:border-amber-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-amber-100 dark:text-amber-950',
      subtextReceived: 'text-amber-500',
      linkSent: 'text-white underline',
      linkReceived: 'text-amber-700 underline'
    },
    previewGradient: 'from-[#fef3c7] to-[#fde68a] dark:from-[#201705] to-[#36270b]',
    badge: '🦁 Wild Safari',
    headerBg: 'bg-[#fef3c7]/90 dark:bg-[#201705]/90 backdrop-blur-md',
    headerBorder: 'border-b border-amber-300 dark:border-amber-900/50',
    headerText: 'text-amber-950 dark:text-amber-100',
    headerSubtext: 'text-amber-700 dark:text-amber-400',
    composerBg: 'bg-[#fde68a]/60 dark:bg-[#181103]',
    composerBorder: 'border-t border-amber-300 dark:border-amber-900/50',
    innerInputBg: 'bg-white dark:bg-[#291e08]',
    innerInputBorder: 'border-amber-400 dark:border-amber-800',
    innerInputText: 'text-amber-950 dark:text-amber-100',
    actionButtonText: 'text-amber-700 dark:text-amber-400',
    actionButtonHoverBg: 'hover:bg-amber-200 dark:hover:bg-amber-950/60',
    actionButtonActiveBg: 'bg-amber-300 dark:bg-amber-900 text-amber-950',
    accentBg: 'bg-amber-600 hover:bg-amber-700 dark:bg-amber-500 dark:hover:bg-amber-400',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },

  // ==================== 4. KIDS & FANTASY (19-24) ====================
  {
    id: 'kids_dino_adventure',
    name: 'Dino Adventure',
    category: 'kids',
    description: 'Fun cartoon dinosaurs & jungle tracks with vibrant green dino controls.',
    bgClass: 'bg-[#ecfdf5] dark:bg-[#061e14] text-emerald-950 dark:text-emerald-100',
    bgStyle: {
      backgroundImage: DINO_ADVENTURE_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '320px 320px',
    },
    bubble: {
      sentBg: 'bg-[#059669] dark:bg-[#34d399]',
      sentText: 'text-white dark:text-slate-950 font-bold',
      receivedBg: 'bg-white dark:bg-[#112f22]',
      receivedText: 'text-emerald-950 dark:text-emerald-100',
      borderStyle: 'border border-emerald-200 dark:border-emerald-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-emerald-100 dark:text-emerald-950',
      subtextReceived: 'text-emerald-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-emerald-600 underline'
    },
    previewGradient: 'from-[#ecfdf5] to-[#a7f3d0] dark:from-[#061e14] to-[#113a29]',
    badge: '🦖 Dino',
    headerBg: 'bg-[#ecfdf5]/90 dark:bg-[#061e14]/90 backdrop-blur-md',
    headerBorder: 'border-b border-emerald-200 dark:border-emerald-900/50',
    headerText: 'text-emerald-950 dark:text-emerald-100',
    headerSubtext: 'text-emerald-600 dark:text-emerald-400',
    composerBg: 'bg-[#d1fae5]/60 dark:bg-[#04140d]',
    composerBorder: 'border-t border-emerald-200 dark:border-emerald-900/50',
    innerInputBg: 'bg-white dark:bg-[#0d261b]',
    innerInputBorder: 'border-emerald-300 dark:border-emerald-800',
    innerInputText: 'text-emerald-950 dark:text-emerald-100',
    actionButtonText: 'text-emerald-600 dark:text-emerald-400',
    actionButtonHoverBg: 'hover:bg-emerald-100 dark:hover:bg-emerald-950/60',
    actionButtonActiveBg: 'bg-emerald-200 dark:bg-emerald-900 text-emerald-800',
    accentBg: 'bg-emerald-600 hover:bg-emerald-500 dark:bg-emerald-400 dark:hover:bg-emerald-300',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },
  {
    id: 'kids_space_rocket',
    name: 'Space Rocket Explorer',
    category: 'kids',
    description: 'Deep cosmic orbit background with rockets, stars, and cyan controls.',
    bgClass: 'bg-[#0f172a] text-cyan-100',
    bgStyle: {
      backgroundColor: '#0f172a',
      backgroundImage: GALAXY_COSMOS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '240px 240px'
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-cyan-500 to-blue-600',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-[#1e293b]',
      receivedText: 'text-cyan-100',
      borderStyle: 'border border-cyan-500/30',
      isSentDark: true,
      isReceivedDark: true,
      subtextSent: 'text-cyan-100/80',
      subtextReceived: 'text-cyan-400/60',
      linkSent: 'text-white underline',
      linkReceived: 'text-cyan-300 underline'
    },
    previewGradient: 'from-[#0f172a] to-[#1e293b]',
    badge: '🚀 Space Rocket',
    headerBg: 'bg-[#0f172a]/90 backdrop-blur-md',
    headerBorder: 'border-b border-cyan-900/60',
    headerText: 'text-cyan-100',
    headerSubtext: 'text-cyan-400',
    composerBg: 'bg-[#0b101d]',
    composerBorder: 'border-t border-cyan-900/60',
    innerInputBg: 'bg-[#1a2333]',
    innerInputBorder: 'border-cyan-800/60',
    innerInputText: 'text-cyan-100',
    actionButtonText: 'text-cyan-400',
    actionButtonHoverBg: 'hover:bg-cyan-950/60',
    actionButtonActiveBg: 'bg-cyan-900/60 text-cyan-200',
    accentBg: 'bg-gradient-to-r from-cyan-500 to-blue-600 hover:brightness-110',
    accentText: 'text-white font-bold'
  },
  {
    id: 'kids_candy_wonderland',
    name: 'Candy Wonderland',
    category: 'kids',
    description: 'Bright lollipop & cupcake pink/cyan theme with vibrant magenta controls.',
    bgClass: 'bg-[#fdf2f8] dark:bg-[#200a18] text-pink-950 dark:text-pink-100',
    bgStyle: {
      backgroundImage: SWEET_CANDY_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '220px 220px'
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-pink-500 to-rose-500',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-white dark:bg-[#301224]',
      receivedText: 'text-pink-950 dark:text-pink-100',
      borderStyle: 'border border-pink-200 dark:border-pink-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-pink-100',
      subtextReceived: 'text-pink-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-pink-600 underline'
    },
    previewGradient: 'from-[#fdf2f8] to-[#fbcfe8] dark:from-[#200a18] to-[#3d122f]',
    badge: '🍭 Candy',
    headerBg: 'bg-[#fdf2f8]/90 dark:bg-[#200a18]/90 backdrop-blur-md',
    headerBorder: 'border-b border-pink-200 dark:border-pink-900/50',
    headerText: 'text-pink-950 dark:text-pink-100',
    headerSubtext: 'text-pink-600 dark:text-pink-400',
    composerBg: 'bg-[#fbcfe8]/60 dark:bg-[#170611]',
    composerBorder: 'border-t border-pink-200 dark:border-pink-900/50',
    innerInputBg: 'bg-white dark:bg-[#2a1020]',
    innerInputBorder: 'border-pink-300 dark:border-pink-800',
    innerInputText: 'text-pink-950 dark:text-pink-100',
    actionButtonText: 'text-pink-600 dark:text-pink-400',
    actionButtonHoverBg: 'hover:bg-pink-100 dark:hover:bg-pink-950/60',
    actionButtonActiveBg: 'bg-pink-200 dark:bg-pink-900 text-pink-800',
    accentBg: 'bg-gradient-to-r from-pink-500 to-rose-500 hover:brightness-110',
    accentText: 'text-white font-bold'
  },
  {
    id: 'kids_magic_rainbow',
    name: 'Magic Rainbow Dreams',
    category: 'kids',
    description: 'Soft pastel rainbow gradient background with electric indigo controls.',
    bgClass: 'bg-[#faf5ff] dark:bg-[#1a0e2a] text-purple-950 dark:text-purple-100',
    bgStyle: {
      backgroundImage: KIDS_WORLD_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '300px 300px'
    },
    bubble: {
      sentBg: 'bg-gradient-to-r from-violet-500 via-purple-500 to-indigo-500',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-white dark:bg-[#2c1746]',
      receivedText: 'text-purple-950 dark:text-purple-100',
      borderStyle: 'border border-purple-200 dark:border-purple-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-purple-100',
      subtextReceived: 'text-purple-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-purple-600 underline'
    },
    previewGradient: 'from-[#faf5ff] to-[#f3e8ff] dark:from-[#1a0e2a] to-[#321a52]',
    badge: '🌈 Magic Rainbow',
    headerBg: 'bg-[#faf5ff]/90 dark:bg-[#1a0e2a]/90 backdrop-blur-md',
    headerBorder: 'border-b border-purple-200 dark:border-purple-900/50',
    headerText: 'text-purple-950 dark:text-purple-100',
    headerSubtext: 'text-purple-600 dark:text-purple-400',
    composerBg: 'bg-[#f3e8ff]/60 dark:bg-[#130a20]',
    composerBorder: 'border-t border-purple-200 dark:border-purple-900/50',
    innerInputBg: 'bg-white dark:bg-[#28143f]',
    innerInputBorder: 'border-purple-300 dark:border-purple-800',
    innerInputText: 'text-purple-950 dark:text-purple-100',
    actionButtonText: 'text-purple-600 dark:text-purple-400',
    actionButtonHoverBg: 'hover:bg-purple-100 dark:hover:bg-purple-950/60',
    actionButtonActiveBg: 'bg-purple-200 dark:bg-purple-900 text-purple-800',
    accentBg: 'bg-gradient-to-r from-violet-500 via-purple-500 to-indigo-500 hover:brightness-110',
    accentText: 'text-white font-bold'
  },
  {
    id: 'kids_toy_box',
    name: 'Playful Toy Box',
    category: 'kids',
    description: 'High-contrast yellow, red & blue toy box vibe with electric blue send button.',
    bgClass: 'bg-[#fefce8] dark:bg-[#1d1904] text-amber-950 dark:text-amber-100',
    bgStyle: {
      backgroundImage: KIDS_WORLD_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '280px 280px'
    },
    bubble: {
      sentBg: 'bg-[#2563eb] dark:bg-[#3b82f6]',
      sentText: 'text-white font-bold',
      receivedBg: 'bg-white dark:bg-[#2c260a]',
      receivedText: 'text-stone-900 dark:text-stone-100',
      borderStyle: 'border border-yellow-300 dark:border-yellow-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-blue-100',
      subtextReceived: 'text-amber-500',
      linkSent: 'text-white underline',
      linkReceived: 'text-blue-600 underline'
    },
    previewGradient: 'from-[#fefce8] to-[#fef08a] dark:from-[#1d1904] to-[#332b07]',
    badge: '🧸 Toy Box',
    headerBg: 'bg-[#fefce8]/90 dark:bg-[#1d1904]/90 backdrop-blur-md',
    headerBorder: 'border-b border-yellow-300 dark:border-yellow-900/50',
    headerText: 'text-amber-950 dark:text-amber-100',
    headerSubtext: 'text-blue-600 dark:text-blue-400',
    composerBg: 'bg-[#fef08a]/60 dark:bg-[#141102]',
    composerBorder: 'border-t border-yellow-300 dark:border-yellow-900/50',
    innerInputBg: 'bg-white dark:bg-[#282208]',
    innerInputBorder: 'border-yellow-400 dark:border-yellow-800',
    innerInputText: 'text-amber-950 dark:text-amber-100',
    actionButtonText: 'text-blue-600 dark:text-blue-400',
    actionButtonHoverBg: 'hover:bg-blue-100 dark:hover:bg-blue-950/60',
    actionButtonActiveBg: 'bg-blue-200 dark:bg-blue-900 text-blue-800',
    accentBg: 'bg-blue-600 hover:bg-blue-500 dark:bg-blue-500 dark:hover:bg-blue-400',
    accentText: 'text-white font-bold'
  },
  {
    id: 'kids_underwater_coral',
    name: 'Underwater Coral Reef',
    category: 'kids',
    description: 'Refreshing aqua sea world with playful coral orange controls.',
    bgClass: 'bg-[#f0fdfa] dark:bg-[#071d1e] text-teal-950 dark:text-teal-100',
    bgStyle: {
      backgroundImage: OCEAN_WAVES_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '180px 180px'
    },
    bubble: {
      sentBg: 'bg-[#0d9488] dark:bg-[#2dd4bf]',
      sentText: 'text-white dark:text-slate-950 font-bold',
      receivedBg: 'bg-white dark:bg-[#122e30]',
      receivedText: 'text-teal-950 dark:text-teal-100',
      borderStyle: 'border border-teal-200 dark:border-teal-900/50',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-teal-100 dark:text-teal-950',
      subtextReceived: 'text-teal-400',
      linkSent: 'text-white underline',
      linkReceived: 'text-teal-600 underline'
    },
    previewGradient: 'from-[#f0fdfa] to-[#ccfbf1] dark:from-[#071d1e] to-[#103437]',
    badge: '🐠 Underwater',
    headerBg: 'bg-[#f0fdfa]/90 dark:bg-[#071d1e]/90 backdrop-blur-md',
    headerBorder: 'border-b border-teal-200 dark:border-teal-900/50',
    headerText: 'text-teal-950 dark:text-teal-100',
    headerSubtext: 'text-teal-600 dark:text-teal-400',
    composerBg: 'bg-[#ccfbf1]/60 dark:bg-[#041314]',
    composerBorder: 'border-t border-teal-200 dark:border-teal-900/50',
    innerInputBg: 'bg-white dark:bg-[#0e2729]',
    innerInputBorder: 'border-teal-300 dark:border-teal-800',
    innerInputText: 'text-teal-950 dark:text-teal-100',
    actionButtonText: 'text-teal-600 dark:text-teal-400',
    actionButtonHoverBg: 'hover:bg-teal-100 dark:hover:bg-teal-950/60',
    actionButtonActiveBg: 'bg-teal-200 dark:bg-teal-900 text-teal-800',
    accentBg: 'bg-teal-600 hover:bg-teal-500 dark:bg-teal-400 dark:hover:bg-teal-300',
    accentText: 'text-white dark:text-slate-950 font-bold'
  },

  // ==================== 5. NATURE & BOTANY (25) ====================
  {
    id: 'nature_emerald_jungle',
    name: 'Emerald Rainforest',
    category: 'nature',
    description: 'Deep rainforest foliage with rich emerald green send controls.',
    bgClass: 'bg-[#062016] text-emerald-100',
    bgStyle: {
      backgroundColor: '#062016',
      backgroundImage: JUNGLE_BOTANICAL_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '220px 220px'
    },
    bubble: {
      sentBg: 'bg-[#10b981]',
      sentText: 'text-slate-950 font-bold',
      receivedBg: 'bg-[#103023]',
      receivedText: 'text-emerald-100',
      borderStyle: 'border border-emerald-500/30',
      isSentDark: false,
      isReceivedDark: true,
      subtextSent: 'text-slate-950/70',
      subtextReceived: 'text-emerald-400/60',
      linkSent: 'text-slate-950 underline',
      linkReceived: 'text-emerald-300 underline'
    },
    previewGradient: 'from-[#062016] to-[#103023]',
    badge: '🌲 Emerald',
    headerBg: 'bg-[#062016]/90 backdrop-blur-md',
    headerBorder: 'border-b border-emerald-900/60',
    headerText: 'text-emerald-100',
    headerSubtext: 'text-emerald-400',
    composerBg: 'bg-[#04160f]',
    composerBorder: 'border-t border-emerald-900/60',
    innerInputBg: 'bg-[#0e291f]',
    innerInputBorder: 'border-emerald-800/60',
    innerInputText: 'text-emerald-100',
    actionButtonText: 'text-emerald-400',
    actionButtonHoverBg: 'hover:bg-emerald-950/60',
    actionButtonActiveBg: 'bg-emerald-900/60 text-emerald-200',
    accentBg: 'bg-emerald-500 hover:bg-emerald-400',
    accentText: 'text-slate-950 font-extrabold'
  }
];
