import React from 'react';
import { ChatTheme } from './themesPart1';
import { 
  JUNGLE_BOTANICAL_PATTERN,
  OCEAN_WAVES_PATTERN,
  LEAVES_PATTERN,
  PROFESSIONAL_TECH_PATTERN,
  CORPORATE_EXECUTIVE_PATTERN,
  PREMIUM_MINIMAL_LINEN,
  WHATSAPP_DOODLE,
  SKY_CLOUDS_PATTERN,
  ZENOA_AESTHETIC_MICRO_PATTERN
} from '../assets/wallpapers';

export const THEMES_PART2: ChatTheme[] = [
  // ==================== 4. NATURE & BOTANY ====================
  {
    id: 'nature_emerald_botanical',
    name: 'Emerald Botanical',
    category: 'nature',
    description: 'Lush botanical foliage with deep forest emerald sent bubbles and organic freshness.',
    bgClass: 'bg-[#f2f9f5] dark:bg-[#0c1712] text-emerald-950 dark:text-emerald-100',
    bgStyle: {
      backgroundImage: JUNGLE_BOTANICAL_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '220px 220px',
    },
    bubble: {
      sentBg: 'bg-emerald-600 dark:bg-emerald-500',
      sentText: 'text-white font-medium',
      receivedBg: 'bg-white dark:bg-[#15241d]',
      receivedText: 'text-emerald-950 dark:text-emerald-100',
      borderStyle: 'border border-emerald-200/80 dark:border-emerald-900/60 shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-emerald-100',
      subtextReceived: 'text-emerald-500',
      linkSent: 'text-white underline font-semibold',
      linkReceived: 'text-emerald-600 dark:text-emerald-400 underline font-medium',
      cardBgSent: 'bg-white/15 border-white/25 text-white',
      cardBgReceived: 'bg-emerald-50 dark:bg-emerald-950/50 border-emerald-200 dark:border-emerald-900 text-emerald-950 dark:text-emerald-100'
    },
    previewGradient: 'from-[#f2f9f5] to-[#a7f3d0] dark:from-[#0c1712] to-[#1a382a]',
    badge: 'Botanical',
    headerBg: 'bg-white/95 dark:bg-[#0c1712]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-emerald-200 dark:border-emerald-950',
    headerText: 'text-emerald-950 dark:text-white',
    headerSubtext: 'text-emerald-600 dark:text-emerald-400',
    composerBg: 'bg-white/95 dark:bg-[#0c1712]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-emerald-200 dark:border-emerald-950',
    innerInputBg: 'bg-emerald-50/80 dark:bg-[#15241d]',
    innerInputBorder: 'border border-emerald-200 dark:border-emerald-900 shadow-xs',
    innerInputText: 'text-emerald-950 dark:text-emerald-100 placeholder:text-emerald-400',
    actionButtonText: 'text-emerald-700 dark:text-emerald-300',
    actionButtonHoverBg: 'hover:bg-emerald-100 dark:hover:bg-emerald-900/50',
    actionButtonActiveBg: 'bg-emerald-600 text-white',
    accentBg: 'bg-emerald-600 hover:bg-emerald-500 shadow-md shadow-emerald-600/25',
    accentText: 'text-white'
  },
  {
    id: 'nature_bamboo_grove',
    name: 'Bamboo Grove',
    category: 'nature',
    description: 'Serene Japanese tea-green canvas with moss sage bubbles and balanced harmony.',
    bgClass: 'bg-[#f4f7f4] dark:bg-[#0f1912] text-[#14532d] dark:text-[#dcfce7]',
    bgStyle: {
      backgroundImage: LEAVES_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '120px 120px',
    },
    bubble: {
      sentBg: 'bg-[#15803d] dark:bg-[#22c55e]',
      sentText: 'text-white dark:text-slate-950 font-medium',
      receivedBg: 'bg-white dark:bg-[#1b2b20]',
      receivedText: 'text-[#14532d] dark:text-[#dcfce7]',
      borderStyle: 'border border-[#bbf7d0] dark:border-[#14532d] shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-green-100 dark:text-green-950',
      subtextReceived: 'text-green-600 dark:text-green-400',
      linkSent: 'text-white underline font-semibold',
      linkReceived: 'text-green-600 dark:text-green-400 underline font-medium',
      cardBgSent: 'bg-white/15 dark:bg-black/15 border-white/25 text-white dark:text-slate-950',
      cardBgReceived: 'bg-green-50 dark:bg-green-950/50 border-green-200 dark:border-green-900 text-green-950 dark:text-green-100'
    },
    previewGradient: 'from-[#f4f7f4] to-[#bbf7d0] dark:from-[#0f1912] to-[#1e3a27]',
    badge: 'Zen',
    headerBg: 'bg-white/95 dark:bg-[#0f1912]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-green-200 dark:border-green-950',
    headerText: 'text-[#14532d] dark:text-white',
    headerSubtext: 'text-green-600 dark:text-green-400',
    composerBg: 'bg-white/95 dark:bg-[#0f1912]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-green-200 dark:border-green-950',
    innerInputBg: 'bg-green-50/80 dark:bg-[#1b2b20]',
    innerInputBorder: 'border border-green-200 dark:border-green-900 shadow-xs',
    innerInputText: 'text-[#14532d] dark:text-[#dcfce7] placeholder:text-green-500',
    actionButtonText: 'text-green-700 dark:text-green-300',
    actionButtonHoverBg: 'hover:bg-green-100 dark:hover:bg-green-900/50',
    actionButtonActiveBg: 'bg-[#15803d] text-white',
    accentBg: 'bg-[#15803d] hover:bg-[#166534] dark:bg-[#22c55e] dark:hover:bg-[#16a34a] shadow-md shadow-green-700/25',
    accentText: 'text-white dark:text-slate-950'
  },
  {
    id: 'nature_ocean_breeze',
    name: 'Ocean Breeze',
    category: 'nature',
    description: 'Crisp coastal seafoam canvas with deep oceanic cobalt send controls and aquatic waves.',
    bgClass: 'bg-[#f0f9ff] dark:bg-[#081524] text-sky-950 dark:text-sky-100',
    bgStyle: {
      backgroundImage: OCEAN_WAVES_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '180px 180px',
    },
    bubble: {
      sentBg: 'bg-cyan-600 dark:bg-cyan-500',
      sentText: 'text-white font-medium',
      receivedBg: 'bg-white dark:bg-[#10243b]',
      receivedText: 'text-sky-950 dark:text-sky-100',
      borderStyle: 'border border-cyan-200/80 dark:border-cyan-900/60 shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-cyan-100',
      subtextReceived: 'text-cyan-500',
      linkSent: 'text-white underline font-semibold',
      linkReceived: 'text-cyan-600 dark:text-cyan-400 underline font-medium',
      cardBgSent: 'bg-white/15 border-white/25 text-white',
      cardBgReceived: 'bg-cyan-50 dark:bg-cyan-950/50 border-cyan-200 dark:border-cyan-900 text-cyan-950 dark:text-cyan-100'
    },
    previewGradient: 'from-[#f0f9ff] to-[#bae6fd] dark:from-[#081524] to-[#153452]',
    badge: 'Oceanic',
    headerBg: 'bg-white/95 dark:bg-[#081524]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-cyan-200 dark:border-cyan-950',
    headerText: 'text-sky-950 dark:text-white',
    headerSubtext: 'text-cyan-600 dark:text-cyan-400',
    composerBg: 'bg-white/95 dark:bg-[#081524]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-cyan-200 dark:border-cyan-950',
    innerInputBg: 'bg-cyan-50/80 dark:bg-[#10243b]',
    innerInputBorder: 'border border-cyan-200 dark:border-cyan-900 shadow-xs',
    innerInputText: 'text-sky-950 dark:text-sky-100 placeholder:text-cyan-400',
    actionButtonText: 'text-cyan-700 dark:text-cyan-300',
    actionButtonHoverBg: 'hover:bg-cyan-100 dark:hover:bg-cyan-900/50',
    actionButtonActiveBg: 'bg-cyan-600 text-white',
    accentBg: 'bg-cyan-600 hover:bg-cyan-500 shadow-md shadow-cyan-600/25',
    accentText: 'text-white'
  },
  {
    id: 'nature_alpine_mist',
    name: 'Alpine Mist',
    category: 'nature',
    description: 'High mountain spruce pine tones with cool frost gray received cards and evergreen bubbles.',
    bgClass: 'bg-[#f0fdf4] dark:bg-[#0b1a14] text-teal-950 dark:text-teal-100',
    bgStyle: {
      backgroundImage: PREMIUM_MINIMAL_LINEN,
      backgroundRepeat: 'repeat',
      backgroundSize: '28px 28px',
    },
    bubble: {
      sentBg: 'bg-teal-700 dark:bg-teal-500',
      sentText: 'text-white font-medium',
      receivedBg: 'bg-white dark:bg-[#132920]',
      receivedText: 'text-teal-950 dark:text-teal-100',
      borderStyle: 'border border-teal-200/80 dark:border-teal-900/60 shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-teal-100',
      subtextReceived: 'text-teal-500',
      linkSent: 'text-white underline font-semibold',
      linkReceived: 'text-teal-600 dark:text-teal-400 underline font-medium',
      cardBgSent: 'bg-white/15 border-white/25 text-white',
      cardBgReceived: 'bg-teal-50 dark:bg-teal-950/50 border-teal-200 dark:border-teal-900 text-teal-950 dark:text-teal-100'
    },
    previewGradient: 'from-[#f0fdf4] to-[#99f6e4] dark:from-[#0b1a14] to-[#183d2e]',
    badge: 'Alpine',
    headerBg: 'bg-white/95 dark:bg-[#0b1a14]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-teal-200 dark:border-teal-950',
    headerText: 'text-teal-950 dark:text-white',
    headerSubtext: 'text-teal-600 dark:text-teal-400',
    composerBg: 'bg-white/95 dark:bg-[#0b1a14]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-teal-200 dark:border-teal-950',
    innerInputBg: 'bg-teal-50/80 dark:bg-[#132920]',
    innerInputBorder: 'border border-teal-200 dark:border-teal-900 shadow-xs',
    innerInputText: 'text-teal-950 dark:text-teal-100 placeholder:text-teal-400',
    actionButtonText: 'text-teal-700 dark:text-teal-300',
    actionButtonHoverBg: 'hover:bg-teal-100 dark:hover:bg-teal-900/50',
    actionButtonActiveBg: 'bg-teal-700 text-white',
    accentBg: 'bg-teal-700 hover:bg-teal-600 shadow-md shadow-teal-700/25',
    accentText: 'text-white'
  },

  // ==================== 5. EXECUTIVE & STUDIO ====================
  {
    id: 'executive_tokyo_slate',
    name: 'Tokyo Slate',
    category: 'executive',
    description: 'Precision architectural slate with graphite bubble contours and sharp modernist typography.',
    bgClass: 'bg-[#f1f5f9] dark:bg-[#0f172a] text-slate-900 dark:text-slate-100',
    bgStyle: {
      backgroundImage: PROFESSIONAL_TECH_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '64px 64px',
    },
    bubble: {
      sentBg: 'bg-slate-800 dark:bg-slate-200',
      sentText: 'text-white dark:text-slate-950 font-medium',
      receivedBg: 'bg-white dark:bg-[#1e293b]',
      receivedText: 'text-slate-900 dark:text-slate-100',
      borderStyle: 'border border-slate-300/80 dark:border-slate-700 shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-slate-300 dark:text-slate-600',
      subtextReceived: 'text-slate-400',
      linkSent: 'text-sky-300 dark:text-sky-700 underline font-semibold',
      linkReceived: 'text-sky-600 dark:text-sky-400 underline font-medium',
      cardBgSent: 'bg-white/10 dark:bg-black/10 border-white/20 dark:border-black/20 text-white dark:text-slate-950',
      cardBgReceived: 'bg-slate-50 dark:bg-slate-800/60 border-slate-200 dark:border-slate-700 text-slate-900 dark:text-slate-100'
    },
    previewGradient: 'from-[#f1f5f9] to-[#cbd5e1] dark:from-[#0f172a] to-[#334155]',
    badge: 'Tokyo',
    headerBg: 'bg-white/95 dark:bg-[#0f172a]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-slate-200 dark:border-slate-800',
    headerText: 'text-slate-900 dark:text-white',
    headerSubtext: 'text-slate-500 dark:text-slate-400',
    composerBg: 'bg-white/95 dark:bg-[#0f172a]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-slate-200 dark:border-slate-800',
    innerInputBg: 'bg-slate-100 dark:bg-[#1e293b]',
    innerInputBorder: 'border border-slate-300 dark:border-slate-700 shadow-xs',
    innerInputText: 'text-slate-900 dark:text-slate-100 placeholder:text-slate-400',
    actionButtonText: 'text-slate-600 dark:text-slate-300',
    actionButtonHoverBg: 'hover:bg-slate-200 dark:hover:bg-slate-800',
    actionButtonActiveBg: 'bg-slate-800 text-white',
    accentBg: 'bg-slate-800 hover:bg-slate-700 dark:bg-slate-200 dark:hover:bg-white shadow-md',
    accentText: 'text-white dark:text-slate-950'
  },
  {
    id: 'executive_silicon_blue',
    name: 'Silicon Blue',
    category: 'executive',
    description: 'Clean enterprise blueprint geometry with royal blue sent bubbles and high-contrast styling.',
    bgClass: 'bg-[#f8fafc] dark:bg-[#0c1322] text-slate-900 dark:text-slate-100',
    bgStyle: {
      backgroundImage: CORPORATE_EXECUTIVE_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '40px 40px',
    },
    bubble: {
      sentBg: 'bg-blue-600 dark:bg-blue-500',
      sentText: 'text-white font-medium',
      receivedBg: 'bg-white dark:bg-[#162035]',
      receivedText: 'text-slate-900 dark:text-slate-100',
      borderStyle: 'border border-blue-200/80 dark:border-blue-900/60 shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-blue-100',
      subtextReceived: 'text-slate-400',
      linkSent: 'text-white underline font-semibold',
      linkReceived: 'text-blue-600 dark:text-blue-400 underline font-medium',
      cardBgSent: 'bg-white/15 border-white/25 text-white',
      cardBgReceived: 'bg-blue-50 dark:bg-blue-950/50 border-blue-200 dark:border-blue-900 text-slate-900 dark:text-slate-100'
    },
    previewGradient: 'from-[#f8fafc] to-[#bfdbfe] dark:from-[#0c1322] to-[#1e3a5f]',
    badge: 'Enterprise',
    headerBg: 'bg-white/95 dark:bg-[#0c1322]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-blue-200 dark:border-blue-950',
    headerText: 'text-slate-900 dark:text-white',
    headerSubtext: 'text-blue-600 dark:text-blue-400',
    composerBg: 'bg-white/95 dark:bg-[#0c1322]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-blue-200 dark:border-blue-950',
    innerInputBg: 'bg-blue-50/80 dark:bg-[#162035]',
    innerInputBorder: 'border border-blue-200 dark:border-blue-900 shadow-xs',
    innerInputText: 'text-slate-900 dark:text-slate-100 placeholder:text-blue-400',
    actionButtonText: 'text-blue-700 dark:text-blue-300',
    actionButtonHoverBg: 'hover:bg-blue-100 dark:hover:bg-blue-900/50',
    actionButtonActiveBg: 'bg-blue-600 text-white',
    accentBg: 'bg-blue-600 hover:bg-blue-500 shadow-md shadow-blue-600/25',
    accentText: 'text-white'
  },
  {
    id: 'executive_carbon_studio',
    name: 'Carbon Studio',
    category: 'executive',
    description: 'High-end titanium graphite weave with smoked glass cards and pure luxury aesthetics.',
    bgClass: 'bg-[#18181b] text-neutral-100',
    bgStyle: {
      backgroundImage: PREMIUM_MINIMAL_LINEN,
      backgroundRepeat: 'repeat',
      backgroundSize: '24px 24px',
    },
    bubble: {
      sentBg: 'bg-neutral-100 text-neutral-950',
      sentText: 'text-neutral-950 font-medium',
      receivedBg: 'bg-[#27272a]',
      receivedText: 'text-neutral-100',
      borderStyle: 'border border-neutral-700 shadow-xs',
      isSentDark: false,
      isReceivedDark: true,
      subtextSent: 'text-neutral-600',
      subtextReceived: 'text-neutral-400',
      linkSent: 'text-indigo-700 underline font-semibold',
      linkReceived: 'text-indigo-400 underline font-medium',
      cardBgSent: 'bg-black/10 border-black/20 text-neutral-950',
      cardBgReceived: 'bg-neutral-800 border-neutral-700 text-neutral-100'
    },
    previewGradient: 'from-[#18181b] to-[#3f3f46]',
    badge: 'Titanium',
    headerBg: 'bg-[#18181b]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-neutral-800',
    headerText: 'text-white',
    headerSubtext: 'text-neutral-400',
    composerBg: 'bg-[#18181b]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-neutral-800',
    innerInputBg: 'bg-[#27272a]',
    innerInputBorder: 'border border-neutral-700 shadow-xs',
    innerInputText: 'text-white placeholder:text-neutral-500',
    actionButtonText: 'text-neutral-400',
    actionButtonHoverBg: 'hover:bg-neutral-800',
    actionButtonActiveBg: 'bg-white text-neutral-950',
    accentBg: 'bg-white hover:bg-neutral-200 shadow-md',
    accentText: 'text-neutral-950'
  },
  {
    id: 'executive_swiss_design',
    name: 'Swiss Modern',
    category: 'executive',
    description: 'International typographic style with bold vermillion red accents and strict architectural grid.',
    bgClass: 'bg-[#ffffff] dark:bg-[#111113] text-black dark:text-white',
    bgStyle: {
      backgroundImage: PROFESSIONAL_TECH_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '48px 48px',
    },
    bubble: {
      sentBg: 'bg-[#dc2626]',
      sentText: 'text-white font-medium',
      receivedBg: 'bg-[#f4f4f5] dark:bg-[#1f1f23]',
      receivedText: 'text-black dark:text-white',
      borderStyle: 'border border-neutral-300 dark:border-neutral-800 shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-red-100',
      subtextReceived: 'text-neutral-500',
      linkSent: 'text-white underline font-semibold',
      linkReceived: 'text-red-600 dark:text-red-400 underline font-medium',
      cardBgSent: 'bg-white/15 border-white/25 text-white',
      cardBgReceived: 'bg-neutral-100 dark:bg-neutral-800/80 border-neutral-200 dark:border-neutral-700 text-black dark:text-white'
    },
    previewGradient: 'from-[#ffffff] to-[#fecaca] dark:from-[#111113] to-[#361616]',
    badge: 'Swiss',
    headerBg: 'bg-white/95 dark:bg-[#111113]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-neutral-200 dark:border-neutral-800',
    headerText: 'text-black dark:text-white',
    headerSubtext: 'text-red-600 dark:text-red-400',
    composerBg: 'bg-white/95 dark:bg-[#111113]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-neutral-200 dark:border-neutral-800',
    innerInputBg: 'bg-neutral-100 dark:bg-[#1f1f23]',
    innerInputBorder: 'border border-neutral-300 dark:border-neutral-700 shadow-xs',
    innerInputText: 'text-black dark:text-white placeholder:text-neutral-400',
    actionButtonText: 'text-neutral-700 dark:text-neutral-300',
    actionButtonHoverBg: 'hover:bg-neutral-200 dark:hover:bg-neutral-800',
    actionButtonActiveBg: 'bg-[#dc2626] text-white',
    accentBg: 'bg-[#dc2626] hover:bg-[#b91c1c] shadow-md shadow-red-600/25',
    accentText: 'text-white'
  },

  // ==================== 6. CLASSIC MESSAGING ====================
  {
    id: 'classic_ios_modern',
    name: 'Cupertino Blue',
    category: 'classic',
    description: 'Iconic iOS messaging layout with signature dynamic blue sent bubbles and sleek frosted cards.',
    bgClass: 'bg-[#f2f2f7] dark:bg-[#000000] text-neutral-900 dark:text-neutral-100',
    bgStyle: {
      backgroundImage: ZENOA_AESTHETIC_MICRO_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '260px 260px',
    },
    bubble: {
      sentBg: 'bg-[#007aff]',
      sentText: 'text-white font-medium',
      receivedBg: 'bg-[#e5e5ea] dark:bg-[#262628]',
      receivedText: 'text-black dark:text-white',
      borderStyle: 'shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-blue-100',
      subtextReceived: 'text-neutral-500',
      linkSent: 'text-white underline font-semibold',
      linkReceived: 'text-[#007aff] underline font-medium',
      cardBgSent: 'bg-white/20 border-white/30 text-white',
      cardBgReceived: 'bg-white/60 dark:bg-black/30 border-black/5 dark:border-white/10 text-black dark:text-white'
    },
    previewGradient: 'from-[#f2f2f7] to-[#93c5fd] dark:from-[#000000] to-[#1e3a8a]',
    badge: 'Cupertino',
    headerBg: 'bg-[#f2f2f7]/95 dark:bg-[#1c1c1e]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-neutral-300/80 dark:border-neutral-800',
    headerText: 'text-black dark:text-white',
    headerSubtext: 'text-neutral-500 dark:text-neutral-400',
    composerBg: 'bg-[#f2f2f7]/95 dark:bg-[#1c1c1e]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-neutral-300/80 dark:border-neutral-800',
    innerInputBg: 'bg-white dark:bg-[#2c2c2e]',
    innerInputBorder: 'border border-neutral-300 dark:border-neutral-700 shadow-xs',
    innerInputText: 'text-black dark:text-white placeholder:text-neutral-400',
    actionButtonText: 'text-[#007aff]',
    actionButtonHoverBg: 'hover:bg-blue-50 dark:hover:bg-blue-950/40',
    actionButtonActiveBg: 'bg-[#007aff] text-white',
    accentBg: 'bg-[#007aff] hover:bg-[#0062cc] shadow-md shadow-blue-500/25',
    accentText: 'text-white'
  },
  {
    id: 'classic_whatsapp_heritage',
    name: 'Emerald Heritage',
    category: 'classic',
    description: 'Heritage doodle background with iconic warm emerald sent bubbles and clean chat cards.',
    bgClass: 'bg-[#efeae2] dark:bg-[#0b141a] text-[#111b21] dark:text-[#e9edef]',
    bgStyle: {
      backgroundImage: WHATSAPP_DOODLE,
      backgroundRepeat: 'repeat',
      backgroundSize: '160px 160px',
    },
    bubble: {
      sentBg: 'bg-[#d9fdd3] dark:bg-[#005c4b]',
      sentText: 'text-[#111b21] dark:text-[#e9edef] font-medium',
      receivedBg: 'bg-white dark:bg-[#202c33]',
      receivedText: 'text-[#111b21] dark:text-[#e9edef]',
      borderStyle: 'shadow-xs border border-black/5 dark:border-white/5',
      isSentDark: false,
      isReceivedDark: false,
      subtextSent: 'text-emerald-800 dark:text-emerald-300',
      subtextReceived: 'text-neutral-500',
      linkSent: 'text-emerald-700 dark:text-emerald-400 underline font-medium',
      linkReceived: 'text-emerald-600 dark:text-emerald-400 underline font-medium',
      cardBgSent: 'bg-emerald-600/10 dark:bg-white/10 border-emerald-600/20 text-[#111b21] dark:text-[#e9edef]',
      cardBgReceived: 'bg-neutral-100 dark:bg-neutral-800/80 border-neutral-200 dark:border-neutral-700 text-[#111b21] dark:text-[#e9edef]'
    },
    previewGradient: 'from-[#efeae2] to-[#bbf7d0] dark:from-[#0b141a] to-[#005c4b]',
    badge: 'Heritage',
    headerBg: 'bg-[#f0f2f5]/95 dark:bg-[#202c33]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-neutral-200 dark:border-neutral-800',
    headerText: 'text-[#111b21] dark:text-[#e9edef]',
    headerSubtext: 'text-[#00a884]',
    composerBg: 'bg-[#f0f2f5]/95 dark:bg-[#202c33]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-neutral-200 dark:border-neutral-800',
    innerInputBg: 'bg-white dark:bg-[#2a3942]',
    innerInputBorder: 'border border-neutral-300 dark:border-neutral-700 shadow-xs',
    innerInputText: 'text-[#111b21] dark:text-[#e9edef] placeholder:text-neutral-400',
    actionButtonText: 'text-[#54656f] dark:text-[#8696a0]',
    actionButtonHoverBg: 'hover:bg-neutral-200 dark:hover:bg-neutral-700',
    actionButtonActiveBg: 'bg-[#00a884] text-white',
    accentBg: 'bg-[#00a884] hover:bg-[#008f72] shadow-md shadow-emerald-600/25',
    accentText: 'text-white'
  },
  {
    id: 'classic_telegram_azure',
    name: 'Telegram Azure',
    category: 'classic',
    description: 'Light cloud sky canvas with signature sky azure sent bubbles and crisp legibility.',
    bgClass: 'bg-[#e7ebf0] dark:bg-[#0e1621] text-[#222222] dark:text-[#f5f5f5]',
    bgStyle: {
      backgroundImage: SKY_CLOUDS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '240px 240px',
    },
    bubble: {
      sentBg: 'bg-[#effdde] dark:bg-[#2b5278]',
      sentText: 'text-[#222222] dark:text-[#f5f5f5] font-medium',
      receivedBg: 'bg-white dark:bg-[#182533]',
      receivedText: 'text-[#222222] dark:text-[#f5f5f5]',
      borderStyle: 'shadow-xs border border-black/5 dark:border-white/5',
      isSentDark: false,
      isReceivedDark: false,
      subtextSent: 'text-sky-800 dark:text-sky-300',
      subtextReceived: 'text-neutral-400',
      linkSent: 'text-[#2481cc] underline font-medium',
      linkReceived: 'text-[#2481cc] underline font-medium',
      cardBgSent: 'bg-sky-500/10 dark:bg-white/10 border-sky-500/20 text-[#222222] dark:text-[#f5f5f5]',
      cardBgReceived: 'bg-neutral-50 dark:bg-neutral-800 border-neutral-200 dark:border-neutral-700 text-[#222222] dark:text-[#f5f5f5]'
    },
    previewGradient: 'from-[#e7ebf0] to-[#bae6fd] dark:from-[#0e1621] to-[#2b5278]',
    badge: 'Azure',
    headerBg: 'bg-white/95 dark:bg-[#17212b]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-neutral-200 dark:border-neutral-800',
    headerText: 'text-[#222222] dark:text-white',
    headerSubtext: 'text-[#2481cc]',
    composerBg: 'bg-white/95 dark:bg-[#17212b]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-neutral-200 dark:border-neutral-800',
    innerInputBg: 'bg-[#f4f4f5] dark:bg-[#242f3d]',
    innerInputBorder: 'border border-neutral-300 dark:border-neutral-700 shadow-xs',
    innerInputText: 'text-[#222222] dark:text-[#f5f5f5] placeholder:text-neutral-400',
    actionButtonText: 'text-[#707579] dark:text-[#7f91a4]',
    actionButtonHoverBg: 'hover:bg-neutral-100 dark:hover:bg-neutral-800',
    actionButtonActiveBg: 'bg-[#2481cc] text-white',
    accentBg: 'bg-[#2481cc] hover:bg-[#1d6fa5] shadow-md shadow-sky-600/25',
    accentText: 'text-white'
  },
  {
    id: 'classic_monochrome',
    name: 'Pure Monochrome',
    category: 'classic',
    description: 'Timeless high-contrast black and white editorial styling with stark graphic impact.',
    bgClass: 'bg-[#ffffff] dark:bg-[#000000] text-black dark:text-white',
    bgStyle: {
      backgroundImage: PREMIUM_MINIMAL_LINEN,
      backgroundRepeat: 'repeat',
      backgroundSize: '30px 30px',
    },
    bubble: {
      sentBg: 'bg-black dark:bg-white',
      sentText: 'text-white dark:text-black font-semibold',
      receivedBg: 'bg-[#f4f4f5] dark:bg-[#18181b]',
      receivedText: 'text-black dark:text-white',
      borderStyle: 'border border-black dark:border-white shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-neutral-400 dark:text-neutral-600',
      subtextReceived: 'text-neutral-500',
      linkSent: 'text-white dark:text-black underline font-bold',
      linkReceived: 'text-black dark:text-white underline font-bold',
      cardBgSent: 'bg-white/10 dark:bg-black/10 border-white/20 dark:border-black/20 text-white dark:text-black',
      cardBgReceived: 'bg-white dark:bg-black border-black dark:border-white text-black dark:text-white'
    },
    previewGradient: 'from-[#ffffff] to-[#e4e4e7] dark:from-[#000000] to-[#27272a]',
    badge: 'Stark',
    headerBg: 'bg-white/95 dark:bg-black/95 backdrop-blur-xl',
    headerBorder: 'border-b border-black dark:border-white',
    headerText: 'text-black dark:text-white',
    headerSubtext: 'text-neutral-600 dark:text-neutral-400',
    composerBg: 'bg-white/95 dark:bg-black/95 backdrop-blur-xl',
    composerBorder: 'border-t border-black dark:border-white',
    innerInputBg: 'bg-[#f4f4f5] dark:bg-[#18181b]',
    innerInputBorder: 'border-2 border-black dark:border-white shadow-xs',
    innerInputText: 'text-black dark:text-white placeholder:text-neutral-500 font-medium',
    actionButtonText: 'text-black dark:text-white',
    actionButtonHoverBg: 'hover:bg-neutral-200 dark:hover:bg-neutral-800',
    actionButtonActiveBg: 'bg-black dark:bg-white text-white dark:text-black',
    accentBg: 'bg-black hover:bg-neutral-800 dark:bg-white dark:hover:bg-neutral-200 shadow-md',
    accentText: 'text-white dark:text-black'
  }
];
