import React from 'react';
import { 
  JUNGLE_BOTANICAL_PATTERN,
  LEAVES_PATTERN,
  OCEAN_WAVES_PATTERN,
  SKY_CLOUDS_PATTERN,
  PROFESSIONAL_TECH_PATTERN,
  CORPORATE_EXECUTIVE_PATTERN,
  WHATSAPP_DOODLE,
  ZENOA_AESTHETIC_MICRO_PATTERN
} from '../assets/wallpapers';
import { ChatTheme } from './themesPart1';

export const THEMES_PART2: ChatTheme[] = [
  // ==================== 4. BOTANICAL & NATURE ====================
  {
    id: 'nature_emerald_botanical',
    name: 'Wild Sage',
    category: 'nature',
    description: 'Calming herbal sage green canvas with organic monstera and eucalyptus leaves and deep evergreen sent bubbles.',
    bgClass: 'bg-[#f1f6f3] dark:bg-[#0e1612] text-[#1a3326] dark:text-[#ebf7f0]',
    bgStyle: {
      backgroundImage: JUNGLE_BOTANICAL_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '380px 380px',
    },
    bubble: {
      sentBg: 'bg-[#183d2a] dark:bg-[#133222]',
      sentText: 'text-[#eefbf4] font-[460]',
      receivedBg: 'bg-white dark:bg-[#16241b]',
      receivedText: 'text-[#1a3326] dark:text-[#ebf7f0]',
      borderStyle: 'border border-[#d4e6db] dark:border-[#22392c] shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-emerald-200/75',
      subtextReceived: 'text-[#577d67] dark:text-[#95bfa6]',
      linkSent: 'text-emerald-200 underline font-semibold decoration-white/50 hover:decoration-white',
      linkReceived: 'text-[#183d2a] dark:text-[#34d399] underline font-medium',
      cardBgSent: 'bg-white/12 border-white/20 text-[#eefbf4]',
      cardBgReceived: 'bg-[#ebf4ef] dark:bg-[#1d2d23] border-[#d4e6db] dark:border-[#2b4435] text-[#1a3326] dark:text-[#ebf7f0]'
    },
    previewGradient: 'from-[#f1f6f3] to-[#cee4d6] dark:from-[#0e1612] to-[#1a3023]',
    badge: 'Botanical',
    headerBg: 'bg-white/95 dark:bg-[#0e1612]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-[#d4e6db] dark:border-[#1c2e23]',
    headerText: 'text-[#1a3326] dark:text-white',
    headerSubtext: 'text-[#577d67] dark:text-[#95bfa6]',
    composerBg: 'bg-white/95 dark:bg-[#0e1612]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-[#d4e6db] dark:border-[#1c2e23]',
    innerInputBg: 'bg-[#e7f1ea] dark:bg-[#16241b]',
    innerInputBorder: 'border border-[#d4e6db] dark:border-[#22392c] shadow-xs',
    innerInputText: 'text-[#1a3326] dark:text-[#ebf7f0] placeholder:text-[#679177]',
    actionButtonText: 'text-[#183d2a] dark:text-[#34d399]',
    actionButtonHoverBg: 'hover:bg-[#d5ebd9] dark:hover:bg-[#1d2d23]',
    actionButtonActiveBg: 'bg-[#183d2a] text-white',
    accentBg: 'bg-[#183d2a] hover:bg-[#112d1f] text-white shadow-xs',
    accentText: 'text-white'
  },
  {
    id: 'nature_ocean_breeze',
    name: 'Pacific Abyss',
    category: 'nature',
    description: 'Marine coastal stone canvas with fluid ocean ripples, nautilus shells, and deep oceanic navy sent bubbles.',
    bgClass: 'bg-[#eff5f8] dark:bg-[#0b141c] text-[#162f40] dark:text-[#edf5fb]',
    bgStyle: {
      backgroundImage: OCEAN_WAVES_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '380px 380px',
    },
    bubble: {
      sentBg: 'bg-[#14364c] dark:bg-[#0e2738]',
      sentText: 'text-[#edf7fc] font-[460]',
      receivedBg: 'bg-white dark:bg-[#12212d]',
      receivedText: 'text-[#162f40] dark:text-[#edf5fb]',
      borderStyle: 'border border-[#d2e4ef] dark:border-[#1e3447] shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-sky-200/75',
      subtextReceived: 'text-[#507891] dark:text-[#91b7cd]',
      linkSent: 'text-sky-200 underline font-semibold decoration-white/50 hover:decoration-white',
      linkReceived: 'text-[#14364c] dark:text-[#38bdf8] underline font-medium',
      cardBgSent: 'bg-white/12 border-white/20 text-[#edf7fc]',
      cardBgReceived: 'bg-[#e8f2f8] dark:bg-[#172b3a] border-[#d2e4ef] dark:border-[#254056] text-[#162f40] dark:text-[#edf5fb]'
    },
    previewGradient: 'from-[#eff5f8] to-[#cbe1ef] dark:from-[#0b141c] to-[#152a3a]',
    badge: 'Pacific',
    headerBg: 'bg-white/95 dark:bg-[#0b141c]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-[#d2e4ef] dark:border-[#162737]',
    headerText: 'text-[#162f40] dark:text-white',
    headerSubtext: 'text-[#507891] dark:text-[#91b7cd]',
    composerBg: 'bg-white/95 dark:bg-[#0b141c]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-[#d2e4ef] dark:border-[#162737]',
    innerInputBg: 'bg-[#e2eef5] dark:bg-[#12212d]',
    innerInputBorder: 'border border-[#d2e4ef] dark:border-[#1e3447] shadow-xs',
    innerInputText: 'text-[#162f40] dark:text-[#edf5fb] placeholder:text-[#648ca4]',
    actionButtonText: 'text-[#14364c] dark:text-[#38bdf8]',
    actionButtonHoverBg: 'hover:bg-[#d2e6f2] dark:hover:bg-[#172b3a]',
    actionButtonActiveBg: 'bg-[#14364c] text-white',
    accentBg: 'bg-[#14364c] hover:bg-[#0d2737] text-white shadow-xs',
    accentText: 'text-white'
  },
  {
    id: 'nature_bamboo_grove',
    name: 'Autumn Cedar',
    category: 'nature',
    description: 'Crisp woodland trail canvas with scattered autumn cedar and bamboo leaves and deep roasted timber bubbles.',
    bgClass: 'bg-[#f8f4ef] dark:bg-[#15120f] text-[#36271c] dark:text-[#f8eee5]',
    bgStyle: {
      backgroundImage: LEAVES_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '360px 360px',
    },
    bubble: {
      sentBg: 'bg-[#3d2719] dark:bg-[#2f1e13]',
      sentText: 'text-[#fdf9f5] font-[460]',
      receivedBg: 'bg-white dark:bg-[#201a15]',
      receivedText: 'text-[#36271c] dark:text-[#f8eee5]',
      borderStyle: 'border border-[#e7ded2] dark:border-[#352a20] shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-amber-200/75',
      subtextReceived: 'text-[#8c7462] dark:text-[#bda897]',
      linkSent: 'text-amber-200 underline font-semibold decoration-white/50 hover:decoration-white',
      linkReceived: 'text-[#3d2719] dark:text-[#fbbf24] underline font-medium',
      cardBgSent: 'bg-white/12 border-white/20 text-white',
      cardBgReceived: 'bg-[#f4eee6] dark:bg-[#282019] border-[#e7ded2] dark:border-[#3d3025] text-[#36271c] dark:text-[#f8eee5]'
    },
    previewGradient: 'from-[#f8f4ef] to-[#e4d7c7] dark:from-[#15120f] to-[#2b1c12]',
    badge: 'Woodland',
    headerBg: 'bg-white/95 dark:bg-[#15120f]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-[#e7ded2] dark:border-[#281f17]',
    headerText: 'text-[#36271c] dark:text-white',
    headerSubtext: 'text-[#8c7462] dark:text-[#bda897]',
    composerBg: 'bg-white/95 dark:bg-[#15120f]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-[#e7ded2] dark:border-[#281f17]',
    innerInputBg: 'bg-[#ede3d7] dark:bg-[#201a15]',
    innerInputBorder: 'border border-[#e7ded2] dark:border-[#352a20] shadow-xs',
    innerInputText: 'text-[#36271c] dark:text-[#f8eee5] placeholder:text-[#9e8774]',
    actionButtonText: 'text-[#3d2719] dark:text-[#fbbf24]',
    actionButtonHoverBg: 'hover:bg-[#e4d8cb] dark:hover:bg-[#282019]',
    actionButtonActiveBg: 'bg-[#3d2719] text-white',
    accentBg: 'bg-[#3d2719] hover:bg-[#2c1b10] text-white shadow-xs',
    accentText: 'text-white'
  },
  {
    id: 'nature_alpine_mist',
    name: 'Highland Moss',
    category: 'nature',
    description: 'Dewy highland moss canvas with organic tea foliage scatter and deep Scottish pine bubbles.',
    bgClass: 'bg-[#f2f6f3] dark:bg-[#0f1613] text-[#1b3125] dark:text-[#ecf7f1]',
    bgStyle: {
      backgroundImage: LEAVES_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '360px 360px',
    },
    bubble: {
      sentBg: 'bg-[#1a3828] dark:bg-[#132c1f]',
      sentText: 'text-[#eefbf4] font-[460]',
      receivedBg: 'bg-white dark:bg-[#15231b]',
      receivedText: 'text-[#1b3125] dark:text-[#ecf7f1]',
      borderStyle: 'border border-[#d5e7db] dark:border-[#22392b] shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-emerald-200/75',
      subtextReceived: 'text-[#567a65] dark:text-[#94beaa]',
      linkSent: 'text-emerald-200 underline font-semibold decoration-white/50 hover:decoration-white',
      linkReceived: 'text-[#1a3828] dark:text-[#34d399] underline font-medium',
      cardBgSent: 'bg-white/12 border-white/20 text-[#eefbf4]',
      cardBgReceived: 'bg-[#ebf4ee] dark:bg-[#1c2c22] border-[#d5e7db] dark:border-[#2b4433] text-[#1b3125] dark:text-[#ecf7f1]'
    },
    previewGradient: 'from-[#f2f6f3] to-[#cde3d4] dark:from-[#0f1613] to-[#182d22]',
    badge: 'Highland',
    headerBg: 'bg-white/95 dark:bg-[#0f1613]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-[#d5e7db] dark:border-[#1a2d21]',
    headerText: 'text-[#1b3125] dark:text-white',
    headerSubtext: 'text-[#567a65] dark:text-[#94beaa]',
    composerBg: 'bg-white/95 dark:bg-[#0f1613]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-[#d5e7db] dark:border-[#1a2d21]',
    innerInputBg: 'bg-[#e7f1eb] dark:bg-[#15231b]',
    innerInputBorder: 'border border-[#d5e7db] dark:border-[#22392b] shadow-xs',
    innerInputText: 'text-[#1b3125] dark:text-[#ecf7f1] placeholder:text-[#658e76]',
    actionButtonText: 'text-[#1a3828] dark:text-[#34d399]',
    actionButtonHoverBg: 'hover:bg-[#d5ebd9] dark:hover:bg-[#1c2c22]',
    actionButtonActiveBg: 'bg-[#1a3828] text-white',
    accentBg: 'bg-[#1a3828] hover:bg-[#11271b] text-white shadow-xs',
    accentText: 'text-white'
  },

  // ==================== 5. STUDIO & EXECUTIVE ====================
  {
    id: 'executive_tokyo_slate',
    name: 'Tokyo Studio',
    category: 'executive',
    description: 'Metropolitan refined stone with drafting coordinates, millimeter lines, and tailored graphite bubbles.',
    bgClass: 'bg-[#f3f4f6] dark:bg-[#101215] text-neutral-900 dark:text-neutral-100',
    bgStyle: {
      backgroundImage: PROFESSIONAL_TECH_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '380px 380px',
    },
    bubble: {
      sentBg: 'bg-[#1e232d] dark:bg-[#171b23]',
      sentText: 'text-[#f8fafc] font-[460]',
      receivedBg: 'bg-white dark:bg-[#171920]',
      receivedText: 'text-neutral-900 dark:text-neutral-100',
      borderStyle: 'border border-neutral-200 dark:border-neutral-800 shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-neutral-300',
      subtextReceived: 'text-neutral-500 dark:text-neutral-400',
      linkSent: 'text-white underline font-semibold decoration-white/50 hover:decoration-white',
      linkReceived: 'text-neutral-800 dark:text-neutral-200 underline font-medium',
      cardBgSent: 'bg-white/10 border-white/20 text-white',
      cardBgReceived: 'bg-neutral-50 dark:bg-neutral-800/60 border-neutral-200 dark:border-neutral-700 text-neutral-900 dark:text-neutral-100'
    },
    previewGradient: 'from-[#f3f4f6] to-[#d1d5db] dark:from-[#101215] to-[#1f242d]',
    badge: 'Tokyo',
    headerBg: 'bg-white/95 dark:bg-[#101215]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-neutral-200 dark:border-neutral-800',
    headerText: 'text-neutral-900 dark:text-white',
    headerSubtext: 'text-neutral-500 dark:text-neutral-400',
    composerBg: 'bg-white/95 dark:bg-[#101215]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-neutral-200 dark:border-neutral-800',
    innerInputBg: 'bg-neutral-100 dark:bg-neutral-800',
    innerInputBorder: 'border border-neutral-300 dark:border-neutral-700 shadow-xs',
    innerInputText: 'text-neutral-900 dark:text-neutral-100 placeholder:text-neutral-400',
    actionButtonText: 'text-neutral-600 dark:text-neutral-300',
    actionButtonHoverBg: 'hover:bg-neutral-200 dark:hover:bg-neutral-700',
    actionButtonActiveBg: 'bg-[#1e232d] text-white',
    accentBg: 'bg-[#1e232d] hover:bg-[#141820] text-white shadow-xs',
    accentText: 'text-white'
  },
  {
    id: 'executive_silicon_blue',
    name: 'Oxford Club',
    category: 'executive',
    description: 'Academic tailored navy canvas with heraldic signet crests and deep Oxford navy sent bubbles.',
    bgClass: 'bg-[#f1f4f8] dark:bg-[#0c121b] text-[#142339] dark:text-[#edf3fb]',
    bgStyle: {
      backgroundImage: CORPORATE_EXECUTIVE_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '380px 380px',
    },
    bubble: {
      sentBg: 'bg-[#152a45] dark:bg-[#102035]',
      sentText: 'text-[#eef4fc] font-[460]',
      receivedBg: 'bg-white dark:bg-[#121b27]',
      receivedText: 'text-[#142339] dark:text-[#edf3fb]',
      borderStyle: 'border border-[#d2e0ee] dark:border-[#1e2f43] shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-blue-200/75',
      subtextReceived: 'text-[#546e8c] dark:text-[#95b0ce]',
      linkSent: 'text-blue-200 underline font-semibold decoration-white/50 hover:decoration-white',
      linkReceived: 'text-[#152a45] dark:text-[#60a5fa] underline font-medium',
      cardBgSent: 'bg-white/12 border-white/20 text-[#eef4fc]',
      cardBgReceived: 'bg-[#ebf2f8] dark:bg-[#182434] border-[#d2e0ee] dark:border-[#253952] text-[#142339] dark:text-[#edf3fb]'
    },
    previewGradient: 'from-[#f1f4f8] to-[#cbdcf0] dark:from-[#0c121b] to-[#162436]',
    badge: 'Oxford',
    headerBg: 'bg-white/95 dark:bg-[#0c121b]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-[#d2e0ee] dark:border-[#162334]',
    headerText: 'text-[#142339] dark:text-white',
    headerSubtext: 'text-[#546e8c] dark:text-[#95b0ce]',
    composerBg: 'bg-white/95 dark:bg-[#0c121b]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-[#d2e0ee] dark:border-[#162334]',
    innerInputBg: 'bg-[#e4edf6] dark:bg-[#121b27]',
    innerInputBorder: 'border border-[#d2e0ee] dark:border-[#1e2f43] shadow-xs',
    innerInputText: 'text-[#142339] dark:text-[#edf3fb] placeholder:text-[#6885a5]',
    actionButtonText: 'text-[#152a45] dark:text-[#93b7dd]',
    actionButtonHoverBg: 'hover:bg-[#d6e3f2] dark:hover:bg-[#182434]',
    actionButtonActiveBg: 'bg-[#152a45] text-white',
    accentBg: 'bg-[#152a45] hover:bg-[#0e1d30] text-white shadow-xs',
    accentText: 'text-white'
  },
  {
    id: 'executive_carbon_studio',
    name: 'Berlin Concrete',
    category: 'executive',
    description: 'Smooth architectural concrete canvas with precision drafting ticks and matte industrial carbon bubbles.',
    bgClass: 'bg-[#eff0f2] dark:bg-[#101114] text-neutral-900 dark:text-neutral-100',
    bgStyle: {
      backgroundImage: PROFESSIONAL_TECH_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '380px 380px',
    },
    bubble: {
      sentBg: 'bg-[#1f1f21] dark:bg-[#19191b]',
      sentText: 'text-white font-[460]',
      receivedBg: 'bg-white dark:bg-[#16181e]',
      receivedText: 'text-neutral-900 dark:text-neutral-100',
      borderStyle: 'border border-neutral-200 dark:border-neutral-800 shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-neutral-400',
      subtextReceived: 'text-neutral-500 dark:text-neutral-400',
      linkSent: 'text-white underline font-semibold decoration-white/50 hover:decoration-white',
      linkReceived: 'text-neutral-800 dark:text-neutral-200 underline font-medium',
      cardBgSent: 'bg-white/10 border-white/20 text-white',
      cardBgReceived: 'bg-neutral-50 dark:bg-neutral-800/60 border-neutral-200 dark:border-neutral-700 text-neutral-900 dark:text-neutral-100'
    },
    previewGradient: 'from-[#eff0f2] to-[#ccd0d6] dark:from-[#101114] to-[#1d1e23]',
    badge: 'Graphite',
    headerBg: 'bg-white/95 dark:bg-[#101114]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-neutral-200 dark:border-neutral-800',
    headerText: 'text-neutral-900 dark:text-white',
    headerSubtext: 'text-neutral-500 dark:text-neutral-400',
    composerBg: 'bg-white/95 dark:bg-[#101114]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-neutral-200 dark:border-neutral-800',
    innerInputBg: 'bg-neutral-100 dark:bg-neutral-800',
    innerInputBorder: 'border border-neutral-300 dark:border-neutral-700 shadow-xs',
    innerInputText: 'text-neutral-900 dark:text-neutral-100 placeholder:text-neutral-400',
    actionButtonText: 'text-neutral-600 dark:text-neutral-300',
    actionButtonHoverBg: 'hover:bg-neutral-200 dark:hover:bg-neutral-700',
    actionButtonActiveBg: 'bg-[#1f1f21] text-white',
    accentBg: 'bg-[#1f1f21] hover:bg-[#141416] text-white shadow-xs',
    accentText: 'text-white'
  },
  {
    id: 'executive_swiss_design',
    name: 'Burnished Bronze',
    category: 'executive',
    description: 'Refined antique bronze canvas with heraldic facets, fountain pen marks, and deep burnished bronze bubbles.',
    bgClass: 'bg-[#f7f4ef] dark:bg-[#15120f] text-[#342518] dark:text-[#faefe5]',
    bgStyle: {
      backgroundImage: CORPORATE_EXECUTIVE_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '380px 380px',
    },
    bubble: {
      sentBg: 'bg-[#3b2515] dark:bg-[#2d1b0d]',
      sentText: 'text-[#fbf7f2] font-[460]',
      receivedBg: 'bg-white dark:bg-[#1e1914]',
      receivedText: 'text-[#342518] dark:text-[#faefe5]',
      borderStyle: 'border border-[#e7ded2] dark:border-[#33271d] shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-amber-200/75',
      subtextReceived: 'text-[#8c735d] dark:text-[#bca793]',
      linkSent: 'text-amber-200 underline font-semibold decoration-white/50 hover:decoration-white',
      linkReceived: 'text-[#3b2515] dark:text-[#f59e0b] underline font-medium',
      cardBgSent: 'bg-white/12 border-white/20 text-white',
      cardBgReceived: 'bg-[#f4eee5] dark:bg-[#261f18] border-[#e7ded2] dark:border-[#3a2d21] text-[#342518] dark:text-[#faefe5]'
    },
    previewGradient: 'from-[#f7f4ef] to-[#e4d7c7] dark:from-[#15120f] to-[#261e16]',
    badge: 'Bronze',
    headerBg: 'bg-white/95 dark:bg-[#15120f]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-[#e7ded2] dark:border-[#271e17]',
    headerText: 'text-[#342518] dark:text-white',
    headerSubtext: 'text-[#8c735d] dark:text-[#bca793]',
    composerBg: 'bg-white/95 dark:bg-[#15120f]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-[#e7ded2] dark:border-[#271e17]',
    innerInputBg: 'bg-[#ece2d5] dark:bg-[#1e1914]',
    innerInputBorder: 'border border-[#e7ded2] dark:border-[#33271d] shadow-xs',
    innerInputText: 'text-[#342518] dark:text-[#faefe5] placeholder:text-[#9e856f]',
    actionButtonText: 'text-[#3b2515] dark:text-[#f59e0b]',
    actionButtonHoverBg: 'hover:bg-[#e2d5c4] dark:hover:bg-[#261f18]',
    actionButtonActiveBg: 'bg-[#3b2515] text-white',
    accentBg: 'bg-[#3b2515] hover:bg-[#2a1a0d] text-white shadow-xs',
    accentText: 'text-white'
  },

  // ==================== 6. SIGNATURE & CLASSIC ====================
  {
    id: 'classic_ios_modern',
    name: 'Zenoa Master',
    category: 'classic',
    description: 'The signature flagship privacy aesthetic with subtle stardust cryptograms and royal indigo-slate bubbles.',
    bgClass: 'bg-[#f4f5fa] dark:bg-[#0c0f18] text-[#192038] dark:text-[#edf0fa]',
    bgStyle: {
      backgroundImage: ZENOA_AESTHETIC_MICRO_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '380px 380px',
    },
    bubble: {
      sentBg: 'bg-[#2b276b] dark:bg-[#201d52]',
      sentText: 'text-[#f4f6ff] font-[460]',
      receivedBg: 'bg-white dark:bg-[#141824]',
      receivedText: 'text-[#192038] dark:text-[#edf0fa]',
      borderStyle: 'border border-[#d5dcee] dark:border-[#21283c] shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-indigo-200/75',
      subtextReceived: 'text-[#5b678e] dark:text-[#9ba6cc]',
      linkSent: 'text-indigo-200 underline font-semibold decoration-white/50 hover:decoration-white',
      linkReceived: 'text-[#2b276b] dark:text-[#818cf8] underline font-medium',
      cardBgSent: 'bg-white/12 border-white/20 text-white',
      cardBgReceived: 'bg-[#edf0f8] dark:bg-[#1a2030] border-[#d5dcee] dark:border-[#29324a] text-[#192038] dark:text-[#edf0fa]'
    },
    previewGradient: 'from-[#f4f5fa] to-[#ced6ee] dark:from-[#0c0f18] to-[#181f32]',
    badge: 'Master',
    headerBg: 'bg-white/95 dark:bg-[#0c0f18]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-[#d5dcee] dark:border-[#1a2032]',
    headerText: 'text-[#192038] dark:text-white',
    headerSubtext: 'text-[#5b678e] dark:text-[#9ba6cc]',
    composerBg: 'bg-white/95 dark:bg-[#0c0f18]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-[#d5dcee] dark:border-[#1a2032]',
    innerInputBg: 'bg-[#e7ebf6] dark:bg-[#141824]',
    innerInputBorder: 'border border-[#d5dcee] dark:border-[#21283c] shadow-xs',
    innerInputText: 'text-[#192038] dark:text-[#edf0fa] placeholder:text-[#707ea8]',
    actionButtonText: 'text-[#2b276b] dark:text-[#96a4d4]',
    actionButtonHoverBg: 'hover:bg-[#dadff2] dark:hover:bg-[#1a2030]',
    actionButtonActiveBg: 'bg-[#2b276b] text-white',
    accentBg: 'bg-[#2b276b] hover:bg-[#201d52] text-white shadow-xs',
    accentText: 'text-white'
  },
  {
    id: 'classic_whatsapp_heritage',
    name: 'Doodle Journal',
    category: 'classic',
    description: 'Vintage unlined cream paper with coffee cups, vinyl records, airplanes, and rich fountain ink bubbles.',
    bgClass: 'bg-[#faf8f2] dark:bg-[#141310] text-[#2c2820] dark:text-[#f8f5eb]',
    bgStyle: {
      backgroundImage: WHATSAPP_DOODLE,
      backgroundRepeat: 'repeat',
      backgroundSize: '380px 380px',
    },
    bubble: {
      sentBg: 'bg-[#1b2535] dark:bg-[#151d2a]',
      sentText: 'text-[#f8fafc] font-[460]',
      receivedBg: 'bg-white dark:bg-[#1c1b16]',
      receivedText: 'text-[#2c2820] dark:text-[#f8f5eb]',
      borderStyle: 'border border-[#e6e2d2] dark:border-[#2e2a22] shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-slate-300',
      subtextReceived: 'text-[#7c745e] dark:text-[#b8af96]',
      linkSent: 'text-sky-200 underline font-semibold decoration-white/50 hover:decoration-white',
      linkReceived: 'text-[#1b2535] dark:text-[#93c5fd] underline font-medium',
      cardBgSent: 'bg-white/12 border-white/20 text-white',
      cardBgReceived: 'bg-[#f5f2e5] dark:bg-[#25231c] border-[#e6e2d2] dark:border-[#383327] text-[#2c2820] dark:text-[#f8f5eb]'
    },
    previewGradient: 'from-[#faf8f2] to-[#e2dec9] dark:from-[#141310] to-[#24221b]',
    badge: 'Journal',
    headerBg: 'bg-white/95 dark:bg-[#141310]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-[#e6e2d2] dark:border-[#26231a]',
    headerText: 'text-[#2c2820] dark:text-white',
    headerSubtext: 'text-[#7c745e] dark:text-[#b8af96]',
    composerBg: 'bg-white/95 dark:bg-[#141310]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-[#e6e2d2] dark:border-[#26231a]',
    innerInputBg: 'bg-[#ede8d8] dark:bg-[#1c1b16]',
    innerInputBorder: 'border border-[#e6e2d2] dark:border-[#2e2a22] shadow-xs',
    innerInputText: 'text-[#2c2820] dark:text-[#f8f5eb] placeholder:text-[#938a70]',
    actionButtonText: 'text-[#1b2535] dark:text-[#c4b998]',
    actionButtonHoverBg: 'hover:bg-[#e2ddd0] dark:hover:bg-[#25231c]',
    actionButtonActiveBg: 'bg-[#1b2535] text-white',
    accentBg: 'bg-[#1b2535] hover:bg-[#131b26] text-white shadow-xs',
    accentText: 'text-white'
  },
  {
    id: 'classic_telegram_azure',
    name: 'Swiss Modern',
    category: 'classic',
    description: 'High-contrast typography canvas with subtle architectural coordinates and pitch matte noir bubbles.',
    bgClass: 'bg-[#fafafa] dark:bg-[#0f0f12] text-neutral-950 dark:text-neutral-50',
    bgStyle: {
      backgroundImage: PROFESSIONAL_TECH_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '380px 380px',
    },
    bubble: {
      sentBg: 'bg-[#111113] dark:bg-[#1f1f23]',
      sentText: 'text-white font-[460]',
      receivedBg: 'bg-white dark:bg-[#18181c]',
      receivedText: 'text-neutral-950 dark:text-neutral-50',
      borderStyle: 'border border-neutral-200 dark:border-neutral-800 shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-neutral-400',
      subtextReceived: 'text-neutral-500 dark:text-neutral-400',
      linkSent: 'text-white underline font-semibold decoration-white/50 hover:decoration-white',
      linkReceived: 'text-neutral-900 dark:text-neutral-100 underline font-medium',
      cardBgSent: 'bg-white/10 border-white/20 text-white',
      cardBgReceived: 'bg-neutral-50 dark:bg-neutral-800/60 border-neutral-200 dark:border-neutral-700 text-neutral-950 dark:text-neutral-50'
    },
    previewGradient: 'from-[#fafafa] to-[#e4e4e7] dark:from-[#0f0f12] to-[#1c1c22]',
    badge: 'Swiss',
    headerBg: 'bg-white/95 dark:bg-[#0f0f12]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-neutral-200 dark:border-neutral-800',
    headerText: 'text-neutral-950 dark:text-white',
    headerSubtext: 'text-neutral-500 dark:text-neutral-400',
    composerBg: 'bg-white/95 dark:bg-[#0f0f12]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-neutral-200 dark:border-neutral-800',
    innerInputBg: 'bg-neutral-100 dark:bg-neutral-800',
    innerInputBorder: 'border border-neutral-300 dark:border-neutral-700 shadow-xs',
    innerInputText: 'text-neutral-950 dark:text-neutral-50 placeholder:text-neutral-400',
    actionButtonText: 'text-neutral-700 dark:text-neutral-300',
    actionButtonHoverBg: 'hover:bg-neutral-200 dark:hover:bg-neutral-700',
    actionButtonActiveBg: 'bg-[#111113] text-white',
    accentBg: 'bg-[#111113] hover:bg-black dark:bg-white dark:hover:bg-neutral-200 text-white dark:text-neutral-900 shadow-xs',
    accentText: 'text-white dark:text-neutral-900'
  },
  {
    id: 'classic_monochrome',
    name: 'Soft Whisper',
    category: 'classic',
    description: 'Airy ethereal canvas with organic whisper cloud ripples and muted lavender-slate bubbles.',
    bgClass: 'bg-[#f6f5fa] dark:bg-[#111017] text-[#231c31] dark:text-[#f3effb]',
    bgStyle: {
      backgroundImage: SKY_CLOUDS_PATTERN,
      backgroundRepeat: 'repeat',
      backgroundSize: '380px 380px',
    },
    bubble: {
      sentBg: 'bg-[#362a4d] dark:bg-[#291e3d]',
      sentText: 'text-[#fcf4ff] font-[460]',
      receivedBg: 'bg-white dark:bg-[#181622]',
      receivedText: 'text-[#231c31] dark:text-[#f3effb]',
      borderStyle: 'border border-[#dfd8ed] dark:border-[#2b243b] shadow-xs',
      isSentDark: true,
      isReceivedDark: false,
      subtextSent: 'text-purple-200/75',
      subtextReceived: 'text-[#76698f] dark:text-[#ad9fc9]',
      linkSent: 'text-purple-200 underline font-semibold decoration-white/50 hover:decoration-white',
      linkReceived: 'text-[#362a4d] dark:text-[#c084fc] underline font-medium',
      cardBgSent: 'bg-white/12 border-white/20 text-white',
      cardBgReceived: 'bg-[#f1edf8] dark:bg-[#211d2c] border-[#dfd8ed] dark:border-[#352c48] text-[#231c31] dark:text-[#f3effb]'
    },
    previewGradient: 'from-[#f6f5fa] to-[#d8d0ea] dark:from-[#111017] to-[#201b2a]',
    badge: 'Whisper',
    headerBg: 'bg-white/95 dark:bg-[#111017]/95 backdrop-blur-xl',
    headerBorder: 'border-b border-[#dfd8ed] dark:border-[#201a2c]',
    headerText: 'text-[#231c31] dark:text-white',
    headerSubtext: 'text-[#76698f] dark:text-[#ad9fc9]',
    composerBg: 'bg-white/95 dark:bg-[#111017]/95 backdrop-blur-xl',
    composerBorder: 'border-t border-[#dfd8ed] dark:border-[#201a2c]',
    innerInputBg: 'bg-[#eae3f3] dark:bg-[#181622]',
    innerInputBorder: 'border border-[#dfd8ed] dark:border-[#2b243b] shadow-xs',
    innerInputText: 'text-[#231c31] dark:text-[#f3effb] placeholder:text-[#8b7ca6]',
    actionButtonText: 'text-[#362a4d] dark:text-[#bdafd9]',
    actionButtonHoverBg: 'hover:bg-[#ded5ed] dark:hover:bg-[#211d2c]',
    actionButtonActiveBg: 'bg-[#362a4d] text-white',
    accentBg: 'bg-[#362a4d] hover:bg-[#281e3a] text-white shadow-xs',
    accentText: 'text-white'
  }
];
